### ISSUE TITLE
video filters

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#112]
Hi,

I've been dancing with the idea of implementing video filters, to provide functionality similar to what the existing audio filters provide.

At first glance, this is pretty straightforward to implement: adapt what exists for audio filters but use the video source and sink.

But...

This will only work if we disabled passthroughs for videos. And that is well, not very good?

I looked at the VideoFrame API in UWP and the IBasicVideoEffect and it does seem to support GPU memory, which should probably be the most effective way to do it. But I am not sure how to convert a VideoFrame to an AvFrame and back again, and probably other issues i cannot see now.

What do you think?

**Comment by lukasf** [comment]
I think that keeping HW acceleration active is pretty important. A lot of devices barely have the power to SW decode the more recent video formats.

But even if IBasicVideoEffect does allow us to use HW acceleration, I think the FFmpeg video effects will only work in system memory. So that would involve a copy from GPU to system memory and back, which might be a performance problem (definitely on 4K videos - maybe also for FullHD).

I think constructing the AVFrame should be possible, although I never tried.

**Comment by mcosmin222** [comment]
We have a first prototype. Check out video-filters.

For the moment it doesn't really work. Video freezes as soon as the effect is applied, it is probably a mismatch of encoding properties similarly to what the audio filter had. I will investigate more in the coming days.

Basically, I think VLC and other players also forego HW acceleration for video filters.

**Comment by lukasf** [comment]
Some video players support Pixel Shader effects, which will work with HW acceleration. But setting that up would be a whole different story.

**Comment by mcosmin222** [comment]
Hmmm good point about the pixel shader. That might actually work with IBasicVideoEffect too.

**Comment by lukasf** [comment]
The msdn docs show how to use HW accelerated IBasicVideoEffect with Win2D (second part of sample):

https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/custom-video-effects

Win2D comes with a lot of effects, which usually work in GPU memory already:

http://microsoft.github.io/Win2D/html/N_Microsoft_Graphics_Canvas_Effects.htm

So there are a lot of effects that come out-of-the-box, where we wouldn't even have to write custom pixel shaders. Using custom PixelShaders is also possible, though more difficult (at least for me, I never really worked with PS):

http://microsoft.github.io/Win2D/html/T_Microsoft_Graphics_Canvas_Effects_PixelShaderEffect.htm

The question is how we could integrate that into the library.

**Comment by mcosmin222** [comment]
I have used compute shaders for math based operations, but it is very tiresome to implement it.
I'd say we go for win2D effects. The ffmpeg based string setup is nice, but the large majority of the filters are not suitable for real time playback.

**Comment by mcosmin222** [comment]
IIRC from when i tried to do this for audio, we need to store the encoding data of the avcodeccontext somewhere and then reload it when the IBasicAudioEffect supported encoding profiles property is called. Last time I used Application data settings, although we could also use a file stream. 

I will give this a try in the coming days.

**Comment by lukasf** [comment]
I think for video this is not even needed. All video must be converted to ARGB for final rendering anyways. So we can just request ARGB32, like in the sample from the first link i posted, and it should work for all formats. MF will insert the neccessary transform filters, if needed.

If any additional data must be provided, we can use SetProperties for that, no need to use ApplicationData.

**Comment by mcosmin222** [comment]
Sounds like a plan.

**Comment by lukasf** [comment]
I have just done some research. Looks like we can do brightness, contrast and saturation very efficiently in one single run, using some fancy combined color matrix operation. If you can setup the basic infrastructure to run Win2D effects, I will try to add in the all-in-one color adjustment effect. ;)

**Comment by mcosmin222** [comment]
Done. I have created the IBasicVideoEffect class, and implemented some of the methods, made it load by default in the CS sample.
Also added the win2D package - used an older version, as the newest one requires a SDK upgrade.

**Comment by lukasf** [comment]
Yesterday I got this working already. I had brightness, contrast and saturation, plus sharpening running on a 4K video, butter smooth! ;)

**Comment by mcosmin222** [comment]
Cool !:)
Sorry for delays, i was a tad busy these past few days.

**Comment by lukasf** [comment]
I just pushed the effect implementation. Check it out! We need to think about how we expose the configuration. An easy to use class would be nice.

Settings can be changed on-the-fly if we edit the IPropertySet during playback. Effects are only used if they are not on default values, otherwise the input image is just copied to output.

**Comment by mcosmin222** [comment]
Hi @lukasf ,
I don't see any new changes in the video-filters branch.

**Comment by lukasf** [comment]
Now it should be there.

**Comment by mcosmin222** [comment]
That is actually pretty impressive. Nice work!

As for how to expose the configuration:
VideoEffectsConfiguration class.

with the 4 properties.
plus a reset method to set them back to default values.

We then expose a static helper method somewhere in our library which will handle adding the effect to a mediaplayer/element object and return its assigned VideoEffectsConfiguration. This could be optional though.

**Comment by mcosmin222** [comment]
I agree it is easier now to consume the effect.

2 things i noticed:

1) there is a random crash with the sliders in the split view. Occurs when sliding off the edge of the pane. 

2) i don't seem to be able to obtain the same images between vlc and the sample with the same adjusted parameters. Our sample effects feel like an overlay on the image rather than changing the image itself.

I will have more time to investigate tomorrow and i will come back with screenshot.

Thanks. And sorry for the bad details ^^

**Comment by lukasf** [comment]
The slider crash is a hard-to-believe-it-is-true UWP bug:

https://github.com/microsoft/microsoft-ui-xaml/issues/477

How hard can it be for a multi-billion-dollar-company to release a simple slider control that does not crash when using it? *facepalm*

I found it is fixed for us when adding a margin to the containing panel.

For the effects, I guess it is a question of how effects are calculated and scaled. I think the sliders work well, except for brightness, which is a big aggressive when moving it down (-0.2 is already very dark).

**Comment by mcosmin222** [comment]
Somehow the bug doesn't surprise me...

**Comment by lukasf** [comment]
Merged with #115

**Comment by mcosmin222** [comment]
Seems video frame server and direct 3D surfaces can be used to do video effects, there's even an example.

https://docs.microsoft.com/en-us/windows/uwp/audio-video-camera/play-audio-and-video-with-mediaplayer#use-mediaplayer-in-frame-server-mode

I do worry that it might not be fast enough though 🤔

**Comment by mcosmin222** [comment]
I did some more research and I think media playback list can never work properly with IBasicVideoEffect interface.

The problem lies with the gapless playback feature of the playback list. In order to do its gapless magic, it needs to gauge the format of the current and next file.

However, as we have recently learned, GPUs typically output nv12 or 10 bit yuv. These are not trivially convertable to ARGB32. So we force the current fileto be argb32 though the effect,  but the next is not. This causes a conflict in opening the current as it needs to be bridge the formats of the 2 items in order to achieve gaplessness.

This will work fine with single source objects like a media playback item.

So in order to do gapless and video effects, the effect needs to be applied before the sample leaves our application. Like we do for audio.

**Comment by lukasf** [comment]
In the end, all video needs to be converted to ARGB, because only that can be rendered on a GPU. NV12, P010 and ll the others are packed formats, which need to be unpacked before rendering. So by forcing the ARGB conversion in IBasicVideoEffect, we only do something that would  be done anyways at a later point. And it does happen on the GPU, HW accelerated.

I do not really believe that it is the different formats that causes MediaPlaybackList to fail. Even without IBasicVideoEffect, videos, as well as audio files, can and will have different output formats. All formats must be converted to a common uncompressed output format, and MF can do that easily. MediaPlaybackList would not work at all if it could not cope with different output formats. I think it's more that the MediaPlaybackList is a buggy implementation. It also has lots of other issues, besides IBasicVideoEffect. Too bad that it's not open source, so we cannot fix it.

I think the better approach would be to apply the effects at the very end. That means, using MediaPlayer in Frame Server mode, and then applying effects to the Surface using Composition APIs. I do not believe that performance would suffer, since this would all happen on the GPU.

Besides that, for a video player, playback does not need to be 100% gapless IMHO. You can do very fast switching by preloading the next file. True gapless is only really required for audio players, when you have mix albums split into multiple files. Then, even a minimal gap can be noticed. At least that is my opinion, so I do not see a need to add MediaPlaybackList into my video player. If you have a MediaPlayer, playing both audio and video, maybe you could also do a hybrid approach: Use MediaPlaybackList for audio files, and switch to single item playback on video files. It's not nice for your code base, but you would get the benefits of gapless audio, without running into issues with video effects.

**Comment by mcosmin222** [comment]
There are video files which are inherently gapless, like those produced by ip cameras. Some models split a larger file into smaller chunks, for rewrite purposes.

I'm not sure about frames server, i fear it will desync audio & video.

**Comment by mcosmin222** [comment]
In the end I did try frame server mode and I must admit, win2D is **incredibly** fast.
I stacked 5 video effects on top of a 4k file and it's not even sweating it.

Added bonus: in frame server mode, the media player element still keeps its usual functions, other than the rendering itself. Luckily, the media player element has an image which renders the poster source, and that image can essentially be used to render the frames in video frame server mode. The media player element will then handle subtitles, the seekbar, fullscreen mode and the such. All one has to do is properly respond to resize and make sure the rendering stops while the application is in the background.

The only thing though is the lack of media casting in frame server mode. But then again, casting video isn't exactly the most efficient thing, and windows usually just connects to the cast target as external display.
