### ISSUE TITLE
 RTMP "Error HRESULT E_FAIL has been returned from a call to a COM component.

### ISSUE THREAD

**Issue by Boo0317** [ffmpeginteropx/FFmpegInteropX#124]
When I open a RTMP url ,it throw an Exception :"Error HRESULT E_FAIL has been returned from a call to a COM component. "And when I test a RTSP url it has no error but it alse doesn't work!!
How can I solve this problem??

**Comment by mcosmin222** [comment]
Hi,

Probably the best thing to do is follow the execution of the code and see where exactly it fails during stream source setup.
For url streaming, we depend completely on ffmpeg doing its magic. So if ffmpeg doesn't support a particular protocol, or if the protocol is not properly implemented by the remote peer, there is little we can do about it.

**Comment by Code-ScottLe** [comment]
It is also throwing this for me when trying to pass in a FFmpegInteropConfig object that has an FFmpegOptions values. For some reason, it doesn't seem to matter when using the MediaPlayerCS sample project.

**Comment by Code-ScottLe** [comment]
Actually, this only happens , even with the MediaPlayerCS project, when you are calling into `CreateFromUriAsync` with the FFmpegInteropOption object which has the FFmpegOptions ValueSet populated with some values. In my case i'm trying to set : 
` Config.FFmpegOptions.Add("protocol_whitelist", "\"rtp,udp\""); `

Is FFmpegOptions supposed to be the arguments to pass in with ffmpeg like it would with command line? (Which i assume)

**Comment by mcosmin222** [comment]
Hi,

Can you provide some urls and test config options?

**Comment by songshizhao** [comment]
here is some url you can test.
"http://vfx.mtime.cn/Video/2019/02/04/mp4/190204084208765161.mp4"
"http://ivi.bupt.edu.cn/hls/cctv6hd.m3u8"
"http://devimages.apple.com.edgekey.net/streaming/examples/bipbop_4x3/gear2/prog_index.m3u8"
"rtmp://live.hkstv.hk.lxdns.com/live/hks"
if i use `mediaElement.MediaPlayer.SetUriSource(new Uri(uriString));`
ms control doing well
but ffmpeg failed with the error above.
I want to know if it is because 'Config.FFmpegOptions' didn't set properly.

**Comment by lukasf** [comment]
@Boo0317 @Code-ScottLe @songshizhao Sorry for the late investigation. There was a problem in stream URI conversion which broke URI streaming. This is solved in "fix-streaming" branch.

@songshizhao I tested the URLs you posted. All of them worked except the rtmp uri, but that one also did not work in any other player. I found this rtmp test URI here and it works correctly on the "fix-streaming" branch:

rtmp://fms.105.net/live/rmc1

Please re-test on the "fix-streaming" branch and let me know if you still face problems.

**Comment by lukasf** [comment]
@Code-ScottLe Most of the command line options can be used, but not all of them (e.g. "out" and some others are ffmpeg.exe exclusive). You can view the list of all allowed options here:

https://www.ffmpeg.org/ffmpeg-protocols.html

When you open a RTMP stream and set protocol_whitelist, you must include rtmp in the list, otherwise it is expected that the call fails. And you must not use quotes.

```
Config.FFmpegOptions.Add("protocol_whitelist", "rtp,udp"); // fails on rtmp stream
Config.FFmpegOptions.Add("protocol_whitelist", "rtp,udp,rtmp"); // this works on rtmp
```

When using the library, you usually do not need to set the whitelist, as all formats are allowed by default. Only use this if you explicitly want to select which kind of sources are allowed.

Sorry for the late response. I had a pretty busy time, and also no one was able to provide test URLs until very recently.

**Comment by lukasf** [comment]
The fix is now available on master branch. Closing this issue.
