### ISSUE TITLE
Creating FFmpegMSS from AdaptiveMediaSource

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#134]
Hi, @lukasf 
I am using now
```
MediaSource  MS = MediaSource.CreateFromAdaptiveMediaSource(AdaptiveMediaSource);
_mediaPlayer.Source = MS;
```
To implement AdaptiveMediaSource playback
Can I create FFmpegMSS from AdaptiveMediaSource?

**Comment by lukasf** [comment]
Hi @sudongg,

The AdaptiveMediaSource already does all the decoding, so you don't really need FFmpegInterop in that scenario right?

You can create a MediaPlaybackItem from either FFmpegInteropMSS or from AdaptiveMediaSource, depending on what you want to play, and then use that MediaPlaybackItem as your common internal format (or some container which handles creation and returns MediaPlaybackItem).

**Comment by mcosmin222** [comment]
Don't you mean the other way around? Adaptive media source from ffmpegMSS?

**Comment by sudongg** [comment]
@lukasf 
Some videos can only be played by creating an AdaptiveMediaSource instead of simply using uri.
But I need to use some functions of FFmpegInteropMSS, such as capturing thumbnails, screenshots, video effects, more format support and so on.
Maybe these functions can be implemented without FFmpegInteropMSS?

**Comment by sudongg** [comment]
@mcosmin222 
I hope FFmpegInteropMSSwill support more network stream video definitions like Adaptive Media Source, rather than just uri

**Comment by lukasf** [comment]
@sudongg 
Have you tried to open the DASH stream URI with FFmpegInterop, using one of the CreateFromUri methods? There is a dashdec.c file in libavformat, so to me it looks like it should be possible to play DASH with ffmpeg (I never tried tough).

I just checked a bit through that code. It looks like FFmpeg will return multiple video streams for DASH (one for each bitrate/resolution variant). So there is no automatic stream switching like in AdaptiveMediaSource. And since FFmpegInterop will only expose the first video stream to UWP, you cannot even manually switch to other streams, you can only hope that the high-res stream is first. Theoretically, we could make multiple video streams available, like we did with the multiple audio streams feature. But then you'd have to do the dynamic switching (not sure how that should work), or allow the user to switch streams manually (there are no stock controls for that).

**Comment by mcosmin222** [comment]
@lukasf ,

AFAIK, there is a build-in control for switching video streams. There's even a sample for that.

**Comment by lukasf** [comment]
Oh ok, I was not aware of that. Still, we'd first have to open up the lib to expose multiple video streams. Otherwise, only the first stream would be rendered.

@sudongg Let us know if you have success rendering DASH with ffmpeg. Otherwise we wouldn't even have to think about multiple video stream support.

**Comment by sudongg** [comment]
@lukasf 
Unable to play DASH stream URI via CreateFromUri. Refer to AdaptiveMediaSource, also need to use HttpClient to add Authentication credentials, custom headers, and then add Mpd information to play DASH video.
Currently, I found a way to add Authentication credentials, custom headers:
https://github.com/kiewic/MediaPlayerElementWithHttpClient
```
HttpClient client = new HttpClient();
Uri uri = new Uri("http://heyhttp.org/song.mp3?basic=1&user=foo&password=bar&lastModified=true");
client.DefaultRequestHeaders.Add("Foo", "Bar");
client.DefaultRequestHeaders.Add("Authorization", "Basic Zm9vOmJhcg==");
HttpRandomAccessStream stream = await HttpRandomAccessStream.CreateAsync(client, uri);
FFmpegMSS = await FFmpegInteropMSS.CreateFromStreamAsync(stream);
```
Implemented the use of FFmpegInterop to play stream that requires Authentication credentials.
But still can not play DASH video, I think playing DASH video also need to add Mpd information. But I couldn't find a way to add it.

**Comment by lukasf** [comment]
The above approach won't work because the initial URI is only a manifest description of the stream. The client will then select the streams and do additional requests, which also need http headers set. This won't work when you do it as above.

I assume that it is possible to set additional http headers in FFmpeg (through FFmpegOptions in our config class) and then use the CreateFromUri method. But I don't know exactly if/how that should work. You will have to look yourself for which ffmpeg options are there.

I don't think that you need to take care of stream internals such as MPD information. FFmpeg should be able to retrieve all required stream details through the manifest files.

**Comment by mcosmin222** [comment]
According to this, ffmpeg does support custom headers, and it seems to use the AvOptions indeed.
https://github.com/FFmpeg/FFmpeg/blob/master/libavformat/http.c

**Comment by lukasf** [comment]
Headers is the raw http header, like this: `<key1>: <value1>\r\n<key2>: <value2>\r\n`

**Comment by sudongg** [comment]
@lukasf 
I tried FFmpegOptions add headers and still couldn't play dash streams, but add headers worked.
Also, during the test I found that FFmpegInterop created streams through CreateFromUri often had incorrect lengths, 30 minutes of streams is only a few minutes. There are also problems with using HttpRandomAccessStream. I use the default MediaSource.CreateFromUrii without this problem. 
And the MediaPlayer_BufferingStarted and MediaPlayer_BufferingEnded events cannot be fired.

**Comment by mcosmin222** [comment]
@sudongg 
I think we are the ones who should trigger the buffering events. But we are not doing any buffering, due to various reasons (mainly performance), so you should not relay on those.

**Comment by lukasf** [comment]
FFmpeg will internally do some buffering on URI sources, and I think you can specifiy the binary buffer size for streams. But I don't think there is a way for us to get the actual buffer status and position, and so we cannot raise those events.

For incorrect stream duration, I don't know why that happens. It might be that FFmpeg only probes a small size of the stream and then initially reports an incorrect duration. Have you tried to play the same stream with ffplay.exe or VLC, to see if they show the right duration?

If you can provide some real stream URIs (including DASH), we could investigate better.

**Comment by sudongg** [comment]
@lukasf 
In addition to the incorrect stream duration, buffer events cannot be triggered, and many videos will have significant stalls during playback. For example http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4, this is the most unacceptable.
My dash url can't be played with CreateFromUriAsync, but it can be played with ffmpegInterop via MediaPlayerElementWithHttpClient I mentioned earlier.
```
HttpClient client = new HttpClient();
HttpRandomAccessStream httpRandomAccessStream = await HttpRandomAccessStream.CreateAsync(client, uri);
FFmpegMSS = await FFmpegInteropMSS.CreateFromStreamAsync(httpRandomAccessStream);
```
This is the dash url for testing from https://www.youtube.com/watch?v=aqkkByP8RDM
video
https://r2---sn-i3b7knse.googlevideo.com/videoplayback?expire=1570778617&ei=mdmfXaLAAY2u4gKy4qtw&ip=42.98.34.45&id=o-ANl_4aNM7ahHJs0EbOaz666bfNdK9PXmtubsMKPe9vQC&itag=135&aitags=133%2C134%2C135%2C160%2C242%2C243%2C244%2C278&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-i3b7knse%2Csn-i3belnez&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=1420000&mime=video%2Fmp4&gir=yes&clen=7548973&dur=467.500&lmt=1538988790018602&mt=1570756896&fvip=2&keepalive=yes&fexp=23842630&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Caitags%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRAIgFTeKq1w5hqK7jZ1orsnnggMhdEEo-8Iz5ht7wVTrrs8CIAJRqUJR7ud0782YrX55Y_loH-eCh4zGXAVgWlTe3krT&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgZ1-GykY6Jpx0G9tSDsfg3Q3p083C59etUbZsF4_Su7ACICxEgW5jii8eaNqp4NenaeBRCrcw8JLIyAiQhCMr1AKD
audio
https://r2---sn-i3b7knse.googlevideo.com/videoplayback?expire=1570778617&ei=mdmfXaLAAY2u4gKy4qtw&ip=42.98.34.45&id=o-ANl_4aNM7ahHJs0EbOaz666bfNdK9PXmtubsMKPe9vQC&itag=140&source=youtube&requiressl=yes&mm=31%2C29&mn=sn-i3b7knse%2Csn-i3belnez&ms=au%2Crdu&mv=m&mvi=1&pl=20&initcwndbps=1420000&mime=audio%2Fmp4&gir=yes&clen=7426580&dur=467.556&lmt=1538988824107527&mt=1570756896&fvip=2&keepalive=yes&fexp=23842630&c=WEB&txp=5432432&sparams=expire%2Cei%2Cip%2Cid%2Citag%2Csource%2Crequiressl%2Cmime%2Cgir%2Cclen%2Cdur%2Clmt&sig=ALgxI2wwRgIhANL5LI9uMlYo8fNnc22qRgv1hgeC1CxaB7swKee6htuXAiEA4_OWamwWDxtw8FHu3I3FIs9gct4zSa2U3njXLabL3gg%3D&lsparams=mm%2Cmn%2Cms%2Cmv%2Cmvi%2Cpl%2Cinitcwndbps&lsig=AHylml4wRAIgZ1-GykY6Jpx0G9tSDsfg3Q3p083C59etUbZsF4_Su7ACICxEgW5jii8eaNqp4NenaeBRCrcw8JLIyAiQhCMr1AKD
