### ISSUE TITLE
Suggest you switch to vcpkg to build ffmpeg

### ISSUE THREAD

**Issue by Noemata** [ffmpeginteropx/FFmpegInteropX#143]
I suspect it will be possible to use vcpkg for the UWP parts of ffmpeg that are required for this.  Would make life a lot easier getting those parts of this project.

.\vcpkg install ffmpeg:x64-uwp --recurse

**Comment by mcosmin222** [comment]
Hello,

I am not very familiar with this tool. Can you explain in more details how it would help us? 

Thanks.

**Comment by lukasf** [comment]
I also have zero knowledge of that tool. I know that there was a branch on the original Microsof repository of that lib, which tried to use vcpkg. But I think they never fully got it working, or at least, it was never merged into master branch.

**Comment by Noemata** [comment]
Looks like it's being updated.  I tried it before making the suggestion, and it was pulling in very recent elements from what I saw.  You might want to have a second look.  The command line I gave you above does all the work for you once you have vcpkg installed.

**Comment by Noemata** [comment]
Here's the list output from vcpkg showing the versions available.  Looks current to me.

ffmpeg               4.2-1            a library to decode, encode, transcode, mux, demux, stream, filter and play pr...
ffmpeg[ffmpeg]                        build the ffmpeg.exe application
ffmpeg[ffserver]                      ffserver appplication support in ffmpeg
ffmpeg[ffplay]                        ffplay appplication support in ffmpeg
ffmpeg[ffprobe]                       ffprobe appplication support in ffmpeg
ffmpeg[openssl]                       openssl support in ffmpeg
ffmpeg[lzma]                          lzma support in ffmpeg
ffmpeg[bzip2]                         bzip2 support in ffmpeg
ffmpeg[vpx]                           WebM VP8/VP9 support in ffmpeg
ffmpeg[x264]                          x264 support in ffmpeg
ffmpeg[opencl]                        opencl support in ffmpeg
ffmpeg[nonfree]                       allow nonfree and unredistributable libraries
ffmpeg[gpl]                           allow GPL licensed libraries
ffmpeg[avresample]                    Libav audio resampling library support in ffmpeg

**Comment by Noemata** [comment]
Just did a quick test.  This is super easy.  When I have a little more time, I'll fork your repo and switch things up to use vcpkg.  In 2 minutes I got all the core sources to build!

**Comment by mcosmin222** [comment]
Can you check of the output is usable in store apps?

**Comment by Noemata** [comment]
Passes the app certification test.  I haven't deployed to the store yet.  Since a lot of Microsoft folks have a hand in vcpkg, I'm guessing this is one of the best ways of getting UWP compliant binaries.

**Comment by Noemata** [comment]
I have everything built and working.  It was remarkably easy to do leveraging vcpkg to pull in the needed libs/includes, and so forth.

I wish I could take credit for doing something.  All I did was adjust the Additional Includes Directories setting to: $(ProjectDir);$(GeneratedFilesDir);$(IntDir);%(AdditionalIncludeDirectories)

I also updated everything to more current Platform SDK releases.  If you'd like I can post the repo, but this is so trivial to do, it would take all of 5 minutes once you installed vcpkg and installed the package as described above.

Thanks the making this so super easy.

**Comment by Noemata** [comment]
P.S. I'm fairly sure I did all of this in under 5 minutes, except for the part of using vcpkg to download and build the needed includes/libs.  It's remarkable folks aren't using vcpkg a lot more!

**Comment by Noemata** [comment]
Screenshot of x64 build, derived from getting ffmpeg includes/libs/etc. using vcpkg.

![image](https://user-images.githubusercontent.com/6632315/68611131-5f0cec80-0487-11ea-911c-d3224287f24c.png)

**Comment by Noemata** [comment]
Screen recording playback of trace log (MP4 file), looks great and uses 15% CPU:

![image](https://user-images.githubusercontent.com/6632315/68612319-43571580-048a-11ea-9dcf-2354c512b02d.png)

**Comment by Noemata** [comment]
I did try loading an RTMP url, that failed.  Should that work through the URI text box?

**Comment by Noemata** [comment]
You can grab my tweaks to your solution here:

https://github.com/Noemata/FFmpegInteropX

I included some details about the trivial changes I made.

**Comment by lukasf** [comment]
I am a bit torn here. On the one hand side, vcpkg really has the potential to ease the ffmpeg build process dramatically, and make out library easily usable by more devs. But on the other hand side, vcpkg has a few major flaws, which give me a bit of a bad feeling.

Most importantly, vcpkg does not include any versioning support. It is impossible to tell vcpkg to build ffmpeg in a specific version, say 4.1. It will only ever build the latest version it knows. If you want to build an older ffmpeg version, you have to go to vcpkg github, browse the history, find the checkout which has added ffmpeg 4.1, copy the commit hash code, then checkout your local vcpkg repo on that hash code, then rebuild the vcpkg from that commit, then use it to build ffmpeg (but be careful, other libs will now also have a different version!). What a horrible dev experience is that? How on earth can Microsoft build a package manager and NOT think about proper versioning support? I really don't know what to say, it's mind blowing.

Also if you have one app which requires lib in version X and one app which requires version Y, the whole "install globally" approach falls apart, just because they did not include version support. You'd have to rebuild the lib each time you switch to the other app, or you have to use other mechanisms (there are indeed other ways to use vcpkg).

If we wanted to use vcpkg, we'd somehow have to deal with this versioning stuff and hide that complexity from devs. Otherwise, we'd trade the old complexity (setup prerequisites) with new complexity (setup vcpkg to build the correct ffmpeg version, and not some "latest" version that potentially breaks our lib). There should be some kind of build script they execute, and it will automatically build the right libraries with the correct version that is required by our lib.

Then there are a few more technical problems: For proper subtitle support, we need to build ffmpeg with zlib, bzip2 and libiconv libs linked. If I understand correctly from checking the ffmpeg support stuff in vcpkg, zlib seems to be automatically included (not 100% sure, needs to be verified) and bzip2 is available as an option. But there is no inuilt option for libiconv, which will break ANSI subtitles for us. Vcpkg seems to have libiconv, but it looks like it does not build for uwp. So first, libiconv would need to be fixed for uwp, then an option must be added to ffmpeg config to allow it to link libiconv into ffmpeg.

If I compare vcpkg ffmpeg build config with ours, I also see some differences. Especially for ARM, we have some additional switches which are not there on vcpkg. Not sure if they are really required, but I think they enable some ARM assembly code optimizations, which might be good to have.

So even if it seems to work for you, there is still quite a lot of work to do, if we wanted to turn this into a proper solution.

**Comment by Noemata** [comment]
I disagree with your premise.  Typically, software development moves only in the forward direction.  You snapshot what you need as you go along.  Vcpkg certainly doesn't preclude you from doing that.  If you need to go into the past now, well, time travel is hard on the psyche.   If now is your starting point, be happy, and make life easy for everyone with tooling that does all the heavy lifting.  If you like to suffer, there are so many better ways to do so than to be mucking with build environments and how to configure things in that special, extra special way.  Getting roasted in the Australian outback might be a more appealing way to suffer.  Lastly, you are free to contribute your ARM build adjustments back to vcpkg, so those special little tweaks get democratized to the masses.

**Comment by lukasf** [comment]
That last post was also kinda hard on the psyche. Holy crap, what did you smoke man?!

**Comment by Noemata** [comment]
Exceptionally cold arctic air.  Yet another way to suffer.  Hence the preference for the Australian outback alternative.

**Comment by mcosmin222** [comment]
What we are trying to say is that we don't always use the latest ffmpeg version in the lib. So versioning is important to us. I personally don't want to go digging in repositories looking for commit hashes.

Another important point to note is that software development doesn't always move forward, especially in the windows store. The certification prevents you from using the latest and greatest if they don't support the store model properly. Recently had this issue with sqlite.

**Comment by Noemata** [comment]
@mcosmin222 when @lukasf asked me what I was smoking, I tried to reply politely.  When I look at things like the instructions here, https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT, I'm inclined to reach for a 26 ouncer of something to dull the pain of it.  Good grief, this sort of build process was out of fashion in the 80s of the last century.  Some folks like the horse and buggy thing.  I'd rather drive a Tesla if given the chance.  No need to reply.  If my 5 minute exercise with vcpkg doesn't convince, nothing will.

**Comment by Noemata** [comment]
Without comment: https://devblogs.microsoft.com/cppblog/vcpkg-2019-06-update/

**Comment by lukasf** [comment]
@Noemata Well, sorry, but to me that post from last evening just came around pretty weird or stoned or arrogant with a touch of "I'm way too cool for your kind of problems" and "anyone who doesn't think that latest is greatest is just sooo lame, and should rather go rot in the australian outback with his old version stuff". I was really hoping that you were just a little drunk or stoned or whatever and tomorrow you'd come up with a proper response.

I never said that I do not consider moving to vcpkg. But I outlined a major problem that vcpkg has. And that is not a theoretical one. Go the vcpkg github, you will find lots of people having problems with the missing versioning capabilities. Lots of people building their own complicated workarounds for something that should be a base functionality on every packet manager.

If we use vcpkg with a "latest is greatest" approach as you propose, I already see people complaining here "your lib does not work", just because they built a newer ffmpeg version that is not yet compatible with our lib. And then we have to tell them: Yeah sorry, wrong ffmpeg version. But don't worry. You just have to search the vcpkg github history, look for the right commit, then manually copy that commit hash, then checkout the vcpkg repsitory on that commit hash, then rebuild the vcpkg tool on that commit, then let the tool rebuild ffmpeg. Oh and be careful, because vcpkg will then also roll back all your other vcpkg libs to different older versions that you probably never even tested with your app, with no way to keep them on what they currently are. Oh, you don't want that, really? So surprised. Well, then, Microsoft recommends you to have separate local vcpkg repositories, one for each lib, check each one out to the proper commit hash you found on github for that lib, build vcpkg on every such branch, and then build the lib on it (and be careful not to build the wrong lib on the wrong vcpkg instance).

Something as simple as checking out a library on a specific version is a horrible nightmare in vcpkg. On every other packet manager on the planet this would be a one-line command.

If we go the vcpkg road, we need to think about how we handle that versioning problem. Should we just go "latest is greatest"? Then we move the problems to all library users. Messing with vcpkg version hell in the long run could easily eat more than the 30 minutes it takes to manually setup the ffmpeg build prerequisites (you only have to do this one time, and you only need to install the tools, our ffmpeg build is fully automatic). Or should we handle vcpkg stuff internally? That means initially more work for us, but less work and trouble for our lib users (and less time for us helping users out). I already have an idea how we could handle it internally, and it might even make some other things easier. I wouldn't go blindly with "latest is greatest" without even considering alternatives, given the fact that vcpkg can cause major trouble and pain.

I also told you that we need libiconv linked, otherwise subtitles won't work properly. For that, we'd first need a uwp compatible build in vcpkg, then we need to add libiconv as a linker option for ffmpeg, configurable in vcpkg. We can sure do that, and yesterday I already looked a bit into how these "ports" work in vcpkg. But I am pretty sure that this will take more than your 5 minutes. You did not even respond to that part.

And do you know why it only took you 5 minutes to get your thing running? Because someone from Mircosoft has already done the work for you and created a uwp compatible build config for ffmpeg and pushed it into the official vcpkg repo. You basically just executed what he configured there. Otherwise, you could not even build ffmpeg-uwp.

**Comment by Noemata** [comment]
I'm old, tired, no longer pretty, and stopped being really cool decades ago.  With that out of the way...  I also must be too dense to understand the problem you are expecting to have.  If I were to move forward with your repo with vcpkg, I would snapshot at every milestone the artifacts generated by vcpkg.  Thus I could easily step back a generation or two and pull backwards changes made in subsequent branches.  Given I'd be pushing out Nuget packages, the task of picking versions is even easier for the consumers of this lib.  Any extra bits I might need I would contribute back to vcpkg, because it's aim is to make life easy for everyone building on Windows.  Perhaps if I was some platform outside of Linux or MacOS, I would lean more heavily on CMAKE.  There's also this curious little capability vcpkg has of being able to export to a Nuget package.  I really, and truly don't get it.  So lets agree to disagree.  Nonetheless, thanks a bunch for making this so easy to adopt.  It took all of 10 minutes to get a nicely bundled Nuget package together using the vcpkg export feature and my favorite nuget editing tool.  So far, the only place I've actually blown time on this is here.  Old == Pedantic must be some sort of truism.

**Comment by Noemata** [comment]
Now if someone else happens to be reading this little discussion and knows of a nice way to merge Nuget packages, please to tell.

**Comment by mcosmin222** [comment]
Well, at this point we could just setup an azure ci machine to do the whole build for us. No need for vcpkg.

**Comment by lukasf** [comment]
I don't see discussions of technical problems as a waste of time.

Manually archiving packages is a workaround for some missing vcpkg functionality, but it only helps once you already have a good build. If people come here for the first time to try the lib, and their build fails or the lib does not work due to incompatible ffmpeg version, then these people will have a problem. And then I have a problem as well, because I will have to support them through all the trouble to get vcpkg build the right ffmpeg version for them. That's what I'd like to avoid. Until now, we could decide which ffmpeg version gets built, and I'd like to keep it that way.

That does not neccessarily mean not using vcpkg. My idea was the following: We include the vcpkg repo as a git submodule of our library repo. That way, we can control on which checkout vcpkg is (and by that, which ffmpeg version it builds). Then we have a build script that will bootstrap vcpkg, build the ffmpeg version and package it as a nuget file. This file gets referenced by the lib, and also by the app that consumes the lib. This has one additional advantage: Currently, the app must manually reference the ffmpeg dlls, and if the dll names change (they include version number), app project files need to be updated. With a nuget package, this should not be required anymore, since contained dlls will be automatically deployed along with the app (at least, I hope so).

Perfect world would be if we have another script that checks if a new ffmpeg version is available. It will do `git submodule update` to sync the vcpkg repo with our repo, then check if now a different ffmpeg version is available, then offer to build that new ffmpeg version.

I found this for merging nuget packages:

https://www.nuget.org/packages/NupkgMerge/

**Comment by lukasf** [comment]
I still consider this as an improvement. But I am not in a hurry, and @Noemata does not seem the be interested in a solution that works for everyone. So I think I will close this, unless someone wants to start with this.

**Comment by mcosmin222** [comment]
I will close this for now, we can have a look at it sometime in the future.
