### ISSUE TITLE
Web assembly support

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#163]
So i have been considering the past few days... How difficult would it be to port this library to support web assembly?

We would surely need to go fully native c++, without the CX extensions and classes, and subtitles would surely not work anymore, but I think it would be a cool, 11/10 difficulty project we could pursue.

**Comment by lukasf** [comment]
WebAssembly sounds cool, since it would allow going cross-platform. But then, I have zero knowledge of WebAssembly. Is there some kind of media playback engine where we could plug into, like we courrently plug into the UWP media framework?

I have to say that my resources are rather limited lately. So frankly, I do not see myself starting major new projects right now.

**Comment by mcosmin222** [comment]
I will keep looking into that. Android on the other hand has a pretty well documented media engine, if you ever fancy trying something new.

**Comment by lukasf** [comment]
Yes I have been looking into Android development a bit. Android has the ExoPlayer, which looks like a pretty cool, extensible media playback framework. Plus, it is open-source. So if you run into bugs, you could debug and solve them, unlike UWP where the only thing you can do is wait and hope.

**Comment by mcosmin222** [comment]
Indeed. Sometimes microsoft just takes toooooooooooo long to fix bugs. Just look at the video filters bug. It is still there after like 8 months.

So do you think we should try moving into android things?

**Comment by lukasf** [comment]
Sooner or later I will try to write a cross-platform app using Uno platform. I don't know if you heard of that. It allows you to run the true full WinUI XAML on Android, iOS and WebAssembly (Native MacOS is also planned I heard), including custom controls, user controls, full styling, suspend/resume, etc etc. That sounds much better to me than the strange Xamarin.Forms XAML dialect, that has a least common denominator approach, lots of custom APIs and lots of missing APIs. I still hope that Microsoft buys Uno for a great Surface Neo/Duo dev story (although time is running out, they'd need to hurry with that). With enough money and dev power from MS, Uno could be turned into something truly awesome.

For the media part, I have not yet seen a promising cross-platform framework yet. I guess best results will only be achieved when you write a native media backend for each platform (including FFmpeg somehow). But the whole UI and most of the app logic could be shared between platforms.

Since you asked for WebAssembly: Did you check out VLC.js? It is a WebAssembly version of VLC, that can be used both as a player and as an engine. I think WebAssembly does not come with any real framework, so you have to roll your own complete media playback engine (and VLC has that). It's still in an early state though (much like almost anything about WebAssembly).

**Comment by mcosmin222** [comment]
I think the biggest issue with using these kind of cross platform frameworks is the inevitable trouble we will have with plugging into the platform's native media engine. I have tried for example to look into using exo player with xamarin android, and it seems there are no bindings available for the interop. 

I did not know about VLC.js, but then again, I suppose VLC has much more power then either me or you to do this kind of things.

**Comment by lukasf** [comment]
There are xamarin bindings:

https://www.nuget.org/packages/Xam.Plugins.Android.ExoPlayer/

Uno recently added support for libvlc, which is probably also not too bad. But sure, plugging into the native media engine and getting it all to work great (e.g. gapless, low resouces, etc) won't be an easy task.

I wouldn't even try to write a complete media playback engine, that would be a gigantic amount of work. So if I'd want to target WebAssembly, I would check what is available there and use that. Maybe extend/customize if needed, but not develop from scratch.

**Comment by mcosmin222** [comment]
I think libVLC is becoming a viable alternative to MF + ffmpeg. It now supports uno and is fully cross platform. So if there's one cross platform media engine, it's probably libVLC.

**Comment by mcosmin222** [comment]
So i gave it a try this weekend, exoplayer and android, and I have to say android APIs are a complete and utter mess. The approach is directly opposite to Windows - instead of minimising background resource usage, they seem to be going the other way around and favor having most of the logic in the background service.

On top of that, heaps of APIs with sane name but different namespace, randomly deprecated things, and unholy need for inner classes.

**Comment by lukasf** [comment]
After reading into discussions about Android APIs, it's also my impression that the situation there is definitely not better than on the Microsoft side. Bugs don't get resolved, APIs get deprecated randomly or just stop working without furher notice, stupid limitations are in place. The grass is always greener on the other side? Huh, well, maybe not. And yes, Android has a very different approach to API design, parly due to Java limitations. Especially, there are no events in Java, so for each and every event you need to implement an interface, what a mess. That's one of the worst aspects of the Java language design.

**Comment by mcosmin222** [comment]
What baffles me more is that kotlin seems to be going down the same route of class / interface for every event handler, instead of implementing actual event handlers. Thank God for Xamarin lol. Makes life a little easier, although interacting with framework classes is still a capital PITA.

I gotta say, Windows is miles ahead of Android. At least backwards compatibility is a given, and bugs are far in between. It is pretty obvious that Microsoft has a much better understanding of the programming world than Google.

**Comment by lukasf** [comment]
I don't fully agree on backwards compatibility: Android has the concept of providing the "AppCompat" layer. It is a set of support libraries that implement new Android APIs on older Android versions as far as possible. So when they deprecate and API and replace it with a new one, you can use AppCompat with the new API and on older phones it will be implemented through the older API. That's a pretty clever concept that allows to evolve APIs and support them even on older phones. But on the other hand it can also be an invitation for Google to randomly break and replace APIs and have devs switch to new concepts all the time.

Overall I also prefer Windows APIs a lot over Android. Especially the UI layer is pretty amazing, if only there were not so many bugs. Hopefully the open source WinUI 3+ will allow it to get even better regarding quality and feature set in future.
