### ISSUE TITLE
Build-FFmpeg.sh - copy to wrong project directory ?

### ISSUE THREAD

**Issue by mediabuff** [ffmpeginteropx/FFmpegInteropX#169]
Should line 128 be
'/p:OutDir="$libs\build\$project\" '
as line 137 is
'Copy-Item $libs\build\$project\'

Right now we have
'/p:OutDir="$libs\build\" '

**Comment by lukasf** [comment]
Unfortunately, the library project files from ShiftMediaProject will append the project name, as well as some other stuff to the OutDir. I wish this was done differently, since it makes the build script a bit hard to understand and maintain. But I don't want to diverge too much from the SMP files. So I leave it as it is and "compensate" inside our own build scripts.
