### ISSUE TITLE
ERROR: libxml-2.0 not found using pkg-config

### ISSUE THREAD

**Issue by pashmak73** [ffmpeginteropx/FFmpegInteropX#170]
Hi, 
I cloned the latest version, and wants to build it.
I tried to build ffmpeg libs but it fails with this error:
`ERROR: libxml-2.0 not found using pkg-config`
libxml is exists in the Libs folder but with no luck.

[build ffmpeg.txt](https://github.com/ffmpeginteropx/FFmpegInteropX/files/4176709/build.ffmpeg.txt)
(Note I couldn't build any platform)

Thanks.

**Comment by lukasf** [comment]
Hi @pashmak73,

you used the old build script, which is obsolete by now. You now have to build ffmpeg using the new powershell script "Build-FFmpeg.ps1". You can either run it directly from powershell:

`.\Build-FFmpeg.ps1`

Or from a normal (non-dev) cmd prompt:

`PowerShell -NoProfile -ExecutionPolicy Bypass -Command ".\Build-FFmpeg.ps1"`

This assumes you are in the FFmpegInteropX folder.

Sorry for the inconvenience. I think we need to either remove the old build script, or change it so that it calls the new PS build script.

**Comment by pashmak73** [comment]
Thanks @lukasf 
Everything is OK for x86/x64 but no luck for ARM and ARM64.

Note: If you have any issue, you may add VS BIN folder to the Windows Path:
`C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin`

Also check these too and change it to whatever you installed in your PC:
https://github.com/ffmpeginteropx/FFmpegInteropX/blob/9608aa7854c996cee98081b342bd07c1a0ee9a7c/Build-FFmpeg.ps1#L6-L16

https://github.com/ffmpeginteropx/FFmpegInteropX/blob/9608aa7854c996cee98081b342bd07c1a0ee9a7c/Build-FFmpeg.ps1#L16-L25
Latest SDK(10.0.18362.0) is installed in my PC but I got error.
So I changed VCVersion to 14.2 and WindowsTargetPlatformVersion to 10.0.17763.0 .


Building ARM and ARM64 failed. here this is ARM logs:

[log.txt](https://github.com/ffmpeginteropx/FFmpegInteropX/files/4177220/log.txt)

**Comment by lukasf** [comment]
Oh yeah there is a bug in later 14.2 compilers that prevents ARM from compiling successfully. If you need ARM, you have to install and select either 14.1 compilers or 14.22. 14.23 and higher have the bug.

The lib should compile fine with 10.0.18362.0. But you can use anything you have installed, since FFmpeg itself does not use any UWP APIs.

**Comment by pashmak73** [comment]
I've installed a lot of C++ libs today, and tried 14.22 14.23 ,14.24 and changed in the ps1 and all of them has that error:
[logss.txt](https://github.com/ffmpeginteropx/FFmpegInteropX/files/4177648/logss.txt)

![image](https://user-images.githubusercontent.com/46992431/74108838-2e764500-4b93-11ea-9553-546807032ad1.png)

![image](https://user-images.githubusercontent.com/46992431/74108843-3b933400-4b93-11ea-92b2-41045ec8bcba.png)
![image](https://user-images.githubusercontent.com/46992431/74108849-44840580-4b93-11ea-808a-544d66165ad6.png)


None of them work.

**Comment by lukasf** [comment]
Oh and you need to update your gas-preprocessor from here:

https://github.com/FFmpeg/gas-preprocessor

**Comment by pashmak73** [comment]
I've updated gas-preprocessor last night, so it shouldn't be that.

**Comment by lukasf** [comment]
The log file you last posted was from 14.24 and it shows the typical errors that ARM has on that compiler version ("it" asm instructions not understood). Please try again with either 14.22 or 14.1 and post logs from that.

You do not need to edit the PS file. You can add the parameters to the command line call:

`.\Build-FFmpeg.ps1 -VcVersion 14.22`

Or from CMD:

`PowerShell -NoProfile -ExecutionPolicy Bypass -Command ".\Build-FFmpeg.ps1 -VcVersion 14.22"`

If you do not need ARM (it is for WP only), you could as well ignore ARM errors and build ARM64:

`.\Build-FFmpeg.ps1 -Platforms ARM64`

Then you have all three PC platforms: x86, x64 and ARM64

**Comment by pashmak73** [comment]
Thanks a lot,
I've been building via 14.21 when I received github email from your reply.
It took too long but it build it successfully.
