### ISSUE TITLE
The MediaPayersCS(UW) program crashed in Hololens2.

### ISSUE THREAD

**Issue by richard008** [ffmpeginteropx/FFmpegInteropX#180]
I tried to use debug mode to start debugging(ARM) and found that an exception is thrown FFmpegInteropLogging at app.xaml.cs .
The stack:
   at System.StubHelpers.StubHelpers.GetWinRTFactoryObject(IntPtr pCPCMD)
   at FFmpegInterop.FFmpegInteropLogging.SetLogLevel(LogLevel level)
   at MediaPlayerCS.App..ctor() in E:\SRC\AR\FFmpegInteropX\Samples\MediaPlayerCS\App.xaml.cs:line 52
   at MediaPlayerCS.Program.<>c.<Main>b__0_0(ApplicationInitializationCallbackParams p) in E:\SRC\AR\FFmpegInteropX\Samples\MediaPlayerCS\obj\ARM\Debug\App.g.i.cs:line 24

The excepotion:
The specified module could not be found. (Exception from HRESULT: 0x8007007E)

The source:
 public App()
        {
            this.InitializeComponent();
            this.Suspending += OnSuspending;
this line:            FFmpegInteropLogging.SetLogLevel(LogLevel.Info);
            FFmpegInteropLogging.SetLogProvider(this);
        }
When I ran the realse version, the program simply crashed.

How can I use the FFmpegInteropX module in hololens2?Or how do I test the FFmpegInteropX module in hololens2?

**Comment by richard008** [comment]
So did in MediaPlayerCPP(UW).

**Comment by lukasf** [comment]
You need to deploy the ffmpeg dll files with your app. This is a bit tricky because you need to copy the right target version of the dlls for every target of your project. Check [this part](https://github.com/ffmpeginteropx/FFmpegInteropX#integrating-ffmpeginterop-into-your-app-solution) of the readme of this repo.

Much easier: Use the new prerelease nuget packets instead. Search "FFmpegInteropX", check "Include prerelease". If you want to be able to debug into our library, reference our library project as you did before, but add the "FFmpegInteropX.FFmpeg" nuget packet to your app project. It contains the ffmpeg dlls for all target versions. If you do not want to debug into FFmpegInteropX, you could even remove our library project and instead add both "FFmpegInteropX" (library only) and "FFmpegInteropX.FFmpeg" (FFmpeg dlls) nuget packets to your ap. Then you do not even need to clone our repo and go nuget only, with the downside that you cannot debug the library code.

The nuget packets are not final yet, but they work well already. Let me know how it goes.

**Comment by lukasf** [comment]
Closing this. Feel free to re-open or create a new issue if you need support.
