### ISSUE TITLE
Minimum subtitle duration 

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#189]
So i encountered a few video files in which the subtitles would stay on for just a couple of milliseconds.

I was wondering if we could add an option to make sure all subtitles have at least a set duration. This could be injected through the configuration file and be changeable during playback.

If the subtitle length is less than the minimum, we set it to minimum. The changes shouldn't be too big.

What do you think @lukasf?

**Comment by lukasf** [comment]
I would also like to add this, I thought about this as well when we did the subtitle stuff. But if you extend the duration like you suppose, then it would cause subtitles to overlap when fast speech occurs. That's what I would like to avoid, because I think it would cause subs to move/jump. My goal would be the extend the duration to the minimum duration, but only until the next subtitle occurs. Since subtitles only come during playback, we might have to reduce the duration of a previous sub (possibly already on screen) when the next one occurs.

But of course, we could first add the simple solution and later we try to extend it to what I had in mind. Maybe have a parameter to toggle between "Normal" and "AvoidOverlap".

**Comment by mcosmin222** [comment]
Cool. I will put together something and then we can improve on it.

**Comment by mcosmin222** [comment]
@lukasf 
Created branch minimum-subtitle-duration

Seems to do the trick fine for my files as long as the minimum duration is set to something sensible.

**Comment by lukasf** [comment]
Hi @mcosmin222 I have pushed a changeset to that branch. It adds the prevent overlap function, plus a second config option "AdditionalSubtitleDuration" which will just extend the subtitle duration with a fixed amount. Some movies remove subs immediately after end of speech. I don't like that, so this is an option I had in mind since some time.

Please check if it works for you and create a PR when ready.

**Comment by lukasf** [comment]
This is already implemented.
