### ISSUE TITLE
FFmpegOptions with low_delay flag is being ignored.

### ISSUE THREAD

**Issue by geniuszombie** [ffmpeginteropx/FFmpegInteropX#191]
Hi, I am trying to play a RTSP stream with low latency. The options that I am providing to FFmpegInteropMSS.CreateFromUriAsync method like follows;

```
private static PropertySet FFmpegOptions => new PropertySet
{
    { "rtsp_transport", "tcp" },
    { "rtsp_flags", "prefer_tcp" },
    { "fflags", "discardcorrupt+shortest+sortdts+ignidx+nobuffer" },
    { "flags", "low_delay" },
    { "allowed_media_types", "video"}
}
```

But somehow FFmpegInteropMSS seems to ignore them. I am experiencing ~500ms latency with this setup.

I am providing the same options to my locally installed ffmpeg instance and it works with almost no latency. 

I am starting the streaming with;
`ffplay -fflags nobuffer -flags low_delay rtsp://URL`

What might be the problem?

**Comment by lukasf** [comment]
Hi @geniuszombie, by default our MSS uses additional buffering of 500ms for all URI sources. You can change this either through the FFmpegInteropConfig class (DefaultBufferTimeUri) or set it on the MSS instance itself (BufferTime property). On live stream sources, you might want to reduce this to zero.

There is always some additional buffering inside MediaFoundation engine. Set MediaPlayer.RealTimePlayback property to minimize buffers in MF layer.

**Comment by mcosmin222** [comment]
You need to be careful with the real time playback property of media player, if your system is not capable of delivering samples in time, you will be faced with pauses and some "clicking" sounds in playback. That property instates a "hard" real time condition which is very unforgiving to performance issues.

**Comment by lukasf** [comment]
Setting our BufferTime to zero might already be enough. The additional MF buffer is pretty small afaik. Just try it and see if it works for you.

**Comment by geniuszombie** [comment]
Than you for the answers. I have tried DefaultBufferTimeUri along with the FFmpegOptions i have mentioned before but there is always some latency that is too big for my project ~500ms. I have also tried the RealTimePlayback  propety of MediaElement and it did some funny things and i figured that it is because SetPlaybackSource method is used to set media stream on sample player projects. After switching to SetMediaStreamSource it is fixed but it did nothing to latency.

So i dig in to FFmpegInterop project to see how things are being handling and i am guessing there are some things about the queuing and calculation of presentation timestamp and duration of the sample frame.

Do you guys have any idea where should i look to achive near zero latency on the playback? Framedroping is no problem for me. I am just trying to display the last frame on the user side as it is generated on the server side. 

Happy to contribute if this use case is a thing for you btw.

**Comment by mcosmin222** [comment]
The queue is there because you sometimes (most of the times) can't build a complete frame out of one package. If that's the case for you, the stream might not be suitable for the type of real time you want to achieve.

May I ask what you are trying to do? It might be that winRT itself might not be suitable for it.

**Comment by lukasf** [comment]
I am guessing that main issue might be that the MF/UWP engine takes a while to setup everything (the time between pressing "return" and playback actually starting). During that time, packets are sent on server side and received by the FFmpeg internal stream handler. Now when playback really starts, packets are played in received order. There is no skip-ahead and I don't know of any API to tell FFmpeg to discard it's stream buffers. There will always be a buffer, no matter what options you pass, it's just that FFmpeg tries to use it as little as possible.

The queue on our side is required for demuxing the stream. There is no way around that and it won't add much latency unless the server does very bad muxing (which does not seem to be the case since it plays fine with FFplay).

I think it would be difficult to implement skip-ahead, since we don't really have control over the stream. There might be ways to work around this, I might give this some more thought.

**Comment by mcosmin222** [comment]
The select filter allows dropping frames

https://ffmpeg.org/ffmpeg-filters.html#select_002c-aselect

Unfortunately, we don't have a video filter implementation, so this would only work for audio only streams.

**Comment by lukasf** [comment]
The thing is that we don't even know how many frames we should drop, because we don't know how much data is in the FFmpeg internal stream buffer.

One way to solve this would be implementing a packet read-ahead buffer on our side. A dedicated read thread would read packets as fast as possible and fill up our queues. Then if a video frame is requested, instead of getting the next packet in queue as we now do, we'd just drop all frames until next keyframe (and drop all audio packets as well until that point).

Such a read-ahead buffer would also help with normal steaming scenraios. But it would be pretty complicated to implement.

**Comment by geniuszombie** [comment]
Hi guys, thank you for the feedbacks. I am trying to drive a remote controlled vehicle just like a drone with FPV. And I have to use H.265 video feed over RTSP w/out audio.  In this scenario, driving it with a ~500ms latency is a good way to crash it somewhere.😁

I was messing around with the codebase and you were right about the queue. It never holds more than one item on my setup and not adding anything up significant to the latency i am experiencing. 

Than I realized this magic number in the calculation of duration and presentation timestamp of the sample in MediaSampleProvider.cpp:185.
```
pts = LONGLONG(av_q2d(m_pAvStream->time_base) * 10000000 * pts) - m_startOffset;
dur = LONGLONG(av_q2d(m_pAvStream->time_base) * 10000000 * dur);
```
I did not understand why it is 10M if it is a second to microsecond conversation (maybe it is not, i am meddling with the powers i do not understand😜) so changed it to 1M and voila!

Now it is working with the options I mentioned before with minimum latency that I can get with ffplay even better. I have simulated all kinds of bad network conditions using [clumsy](https://jagt.github.io/clumsy/) and it always recovers from them. I could not be able to test on lower hardware configuration yet but I will do soon.

So what do you think? Did I brake something there?

**Comment by lukasf** [comment]
The 10M factor is there to translate PTS/DTS seconds into TimeSpan. A TimeSpan uses Ticks as unit, and 10M Ticks are one second. So with this change, you are speeding up the timestamps by a factor of 10.

So yes, you are somehow breaking/hacking it. The MediaFoundation engine will try to play at 10x speed, but of course, the server does not deliver at that speed, so it plays as fast as it can. This is more like a hack, but it could work for you. Just make sure that audio and video plays fine in differnt scenarios.

If you would do that with local files, you would sure run into trouble when trying to seek in the file. But since you only play streaming video, it could work out ok.

**Comment by mcosmin222** [comment]
As long as you keep the same hack for both audio and video, they should be safely in sync. Ofc audio will be useless and you will probably hear a buzzing sound.

**Comment by lukasf** [comment]
Closing this, the hack seems to work.
