### ISSUE TITLE
Get Timecode from video stream

### ISSUE THREAD

**Issue by jjouppi** [ffmpeginteropx/FFmpegInteropX#194]
Hey all!

Wondering if there is a way to get accurate time-code from an ffmpeg video stream while using FFmpegInteropX? Right now I'm approximating from the media player position in milliseconds but the rounding is invariably a tad off making the frame counter unreliable.

```
var playerMilliseconds = mediaElement.MediaPlayer.PlaybackSession.Position.TotalMilliseconds;

var frameMath = ((Math.Round(playerMilliseconds, MidpointRounding.ToEven) / (Math.Round(10 / mediaFrameRate, 4, MidpointRounding.AwayFromZero)) * 10));

var frameCounts = Math.Floor(frameMath / 1000);

FrameNumber.Text = "- " + frameCounts;
```
This all results in a frame number that's mostly accurate but as you are scubbing there's an occasion where this value is off by a frame.

I see there's some reference to timecode in the FFmpeg documentation and wondering if it's possible to access that information while using FFmpeginteropx?

Thanks and apologies if this is the wrong place for this question.

**Comment by lukasf** [comment]
Hi @jjouppi, I don't think that we can do this through the library. The playback engine has its own internal buffering. So usually, when you play/seek to frame X, we have already decoded X+1, X+2, etc. in our lib. So we can't just use the last decoded frame number. And we don't know which of the last decoded frames you are actually looking at.

I don't fully understand your calculation logic, but I think you should remove all the roundings in `var frameMath = ...` line. Just leave this all as unrounded double, and use Math.Floor as you do at the end. It might improve your accuracy.

**Comment by mcosmin222** [comment]
I think you can use the sample rendered event as well. But i don't think it will be much more accurate than the playback position.

**Comment by lukasf** [comment]
The MediaStreamSource.SampleRendered event only has a property to get the lag. But you won't know which sample was actually rendered, so it does not really help you.

**Comment by mcosmin222** [comment]
Ah sorry, i meant this one

https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediastreamsample.processed?view=winrt-19041

**Comment by lukasf** [comment]
That one only means that the sample has been processed by the downstream filter (e.g. decoder). Behind the downstream filter there will usually be more buffering (e.g. decoded frames are buffered by the video renderer).

**Comment by mcosmin222** [comment]
Yes, agreed, which is why I don't think it will provide a better estimation than the playback position itself.

**Comment by jjouppi** [comment]
@lukasf @mcosmin222  thank you both for looking into it and for your ideas. Yeah it seems the best process is to get the player position, convert that to frames, and then convert that into SMPTE timecode.

Overall, the main two problems that remain are:

**1. Accurate Play/Pause frame total**
Currently when the player starts playing and then is paused, the frame total continues be offset by 1-2 frames. If you grab the progress bar thumb or click the timeline to scrub through the video, the frame total returns to the correct frame value. I'm wondering if offset is caused by some delay between when the pause button is click and when the frame total stops counting? 

**2. Accurate Dropframe frame total**
For dropframe media (23.976fps, 29.97fps, 59.94fps) I'm still getting occasional 1-2 frame variations in the frame total. I can't seem to figure out what is causing this.

I've found that I'm able to get an accurate frame count and SMPTE timecode while scrubbing through non-dropframe video. One thing that helped was to increase the step frequency on the progress bar slider in my custom transport controls. Here's what I ended up with (thanks for suggesting I remove the rounding @lukasf):

```
using Timecode4net;

//These variables set when opening a file with filepicker
public double mediaFrameRate { get; set; }
public FrameRate TC4NetFrameRate { get; set; }  //FrameRate.fps30;
public bool IsDropFrame { get; set; }

public int totalFrames { get; set; } = 0;
public double playerSeconds { get; set; } = 0;

public MainPage()
{
    DispatcherTimer timer = new DispatcherTimer();
    timer.Interval = TimeSpan.FromMilliseconds(0.01);
    timer.Tick += Timer_Tick;
    timer.Start();
}

private void Timer_Tick(object sender, object e)
{
    playerSeconds = mediaElement.MediaPlayer.PlaybackSession.Position.TotalSeconds;
    totalFrames = (int)Math.Floor(playerSeconds * mediaFrameRate);
    var tcFromFrames = Timecode.FromFrames(totalFrames, TC4NetFrameRate, IsDropFrame);

    FrameNumber.Text = tcFromFrames + " - " + totalFrames;
 }
 
```
After working on converting to SMPTE for a while, I found the TimeCode4Net NuGet: https://github.com/ailen0ada/Timecode4net

Using that, I was able to convert the total frames to SMPTE timecode using the following:

`var tcFromFrames = Timecode.FromFrames(totalFrames, TC4NetFrameRate, IsDropFrame);`

If I get this working a bit better and it seems useful, I'd love to add it to FFmpeginteropX. I'm new to development so not totally sure how I'd do that but it's on my list of things to figure out.

Thanks again for this great repository and for all your help!

**Comment by lukasf** [comment]
Glad to hear that you could improve accuracy with the steps you mentioned. I also don't understand why they use such a bad step frequency by default on the progress bar. It's no problem to increase it to 10000 or even higher, to get very precise seeking.

However, if you absolutely need 100% accuracy, then using MediaPlayer might not be the right tool for the job. Since it is closed source, you won't be able to fix the bugs in its position handling.

Do you need normal playback as well, or do you only step through frames? If you only step through frames, you could as well use our FrameGrabber and put the images in an Image control. The FrameGrabber allows you to precisely grab frames, one after the other, without relying on MediaPlayer and its (seemingly broken) position handling. Each frame has a precise timestamp. Only downside is that the de-interlacing won't be as good, since it is not done by GPU HW algorithms.

About frame dropping: I was not aware of the rules used there, thanks for the information. However, I wouldn't bet that MediaPlayer uses the exact same rules. I'd try to pass IsFrameDrop=false in your library and see if precision gets better.

Did you know that most displays support a refresh rate of "59 Hz" (sometimes called 59p)? This is in reality 59.94 Hz and will allow 100% smooth playback without frame drops for 59.94 as well as 29.97 fps media. Plus, it also helps with 23.976 fps media and makes it smoother. It could help you when editing these files. Be sure to use IsFrameDrop=false in that case.

For 100% smooth playback of 23.976 fps media, you'd have to use "23 Hz" refresh rate. Personally, I always use 59 Hz on devices that I also use for movie playback. For me it is the best compromise between good media playback and good fast windows use. 23 Hz is obviously way too slow to do real work on a PC. Most laptop displays unfortunately only support 60Hz, which is why you won't be able to get 100% smooth playback there, unless your media is (exactly) 30fps or 60fps.

**Comment by mcosmin222** [comment]
I once tried increasing the accuracy on the seekbar, the performance quickly went down on long files. I think they are limited by the UWP xaml slider.

You can also try frame server mode for MediaPlayer.

**Comment by jjouppi** [comment]
Hey for future reference, timecode for my player was off by 1-2 frames whenever a user pressed pause due to a slight delay between when my timecode reader stopped counting and the video playback actually paused. I was able to fix this by adding a delay then moving the player forward by a single frame whenever the play/pause button was pressed:

`private async void PlayPauseButton_Click(object sender, RoutedEventArgs e)
        {


            if (mediaElement.MediaPlayer.PlaybackSession.PlaybackState == MediaPlaybackState.Playing)
            {
                await Task.Delay(15);

                TimeSpan frameForward = TimeSpan.FromSeconds(playerSeconds + frameIncrement);

                mediaElement.MediaPlayer.PlaybackSession.Position = (frameForward);
            }
       }`

**Comment by lukasf** [comment]
Hi @jjouppi, glad to hear that you could find a solution to your problem. The downside of setting the position is that this will lead to a seek operation, usually followed by a bunch of frame decodes (from previous keyframe until target position). So pause/unpause will cost you a bit of performance. It might not even matter much, just saying. Did you try the method "StepForwardOneFrame()" on MediaPlayer? This should get you to the next frame without a seek operation. You'll have to check though if this still gives you a correct timecode.

**Comment by lukasf** [comment]
Closing this since you found a good solution. Feel free to re-open or create a new issue at any time.
