### ISSUE TITLE
Wmv video seek error

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#195]
Hi @lukasf 
I am testing the latest version FFmpegInteropX. (master branch)
The wmv format can be played, but there was a problem during seek.
Sample link: 
https://www.dropbox.com/s/y1459e4mxpted3d/WMV%20Sample.zip?dl=0
This video can only seek forward, not backward, and the backward seek video will stop.

**Comment by lukasf** [comment]
Oh yeah I had also noticed this with a few files in the past, but I never investigated it. Looks like these files do not carry a PTS value. We calculate PTS based on duration for these files, but that approach fails after a seek. I now added a workaround to use DTS instead of PTS after a seek, if PTS is not available. This seems to work pretty well. I pushed the fix to the fast-seeking branch, please check if it works for you.

**Comment by sudongg** [comment]
@lukasf 
Thanks. The problem has been solved.
