### ISSUE TITLE
Audio stream with fractional frame duration

### ISSUE THREAD

**Issue by mcosmin222** [ffmpeginteropx/FFmpegInteropX#196]
Hello @lukasf,

I came across a file containing an audio stream which has fewer samples per frame than the sampling rate of the audio stream descriptor, and this causes our library to assume the frame duration is always 0.

The problem occurs in UncompressAudioSampleProvider::CreateBufferFromFrame

at line:
auto actualDuration = (long long)avFrame->nb_samples * m_pAvStream->time_base.den / (outSampleRate * m_pAvStream->time_base.num);

In this cases, nb_samples is 40, while outSamplingRate is 48000, timebase is 1/1000

The file plays fine in VLC, but video app in windows can't handle it either.

My first reaction to this would be to consider all frame durations as doubles until we get to the ticks conversion, at which point we can make them integers by multiplying with 100000000.

What do you think?

Edit: just tried it, it doesn't work ^^

**Comment by lukasf** [comment]
It's strange because you said that this file played fine in the past. So looks like there was a change in FFmpeg that breaks it.

What happens if you just check if the result duration is 0 and manually round up to 1? Or change `if (frameDuration != actualDuration)` to `if (frameDuration != actualDuration && actualDuration > 0)`?

If we'd change the data type, I'd rather go to TimeSpan directly. But it seems that it does not even help. If you can create a sample from that file, I could also take a look.

**Comment by mcosmin222** [comment]
Amazingly, patching it up to 1 really did work. I expected this to cause weird sound artifacts, but it didn't. 

I simply added 
if (actualDuration == 0)actualDuration = 1;

and it seems to do the trick. I will give it some more tests and come back with a PR later.

**Comment by lukasf** [comment]
Cool, yeah I was hoping that this would work. With TimeSpan, it is usually not possible to exactly specify timestamps and durations. I don't know why MS did not use rationals for MSS, like FFmpeg and any other major media framework (including MediaFoundation) does. But since they use TimeSpan, they have to re-calculate sample durations, which helps us here.

**Comment by mcosmin222** [comment]
Ah that explains why it didn't work when I tried to do fractional timespans with doubles.
