### ISSUE TITLE
Is it possible to have a nuget package with https support?

### ISSUE THREAD

**Issue by TaoziDB** [ffmpeginteropx/FFmpegInteropX#206]
More and more online videos are using https protocol, a nuget package with https support will definitely help, thanks.

**Comment by lukasf** [comment]
Hi @TaoziDB, I tried to get FFmpeg to compile with GnuTLS but it failed for me. The build setup is very complicated with lots of required submodules. The other option is using openssl. @villagra tried to integrate it, see #179, but I think it was not successful yet. Current Openssl has a bad license, forcing you to put advertisements in all app descriptions. Openssl 3 will have a much better license. It is planned for end of the year.

If someone can show how to build FFmpeg with either openssl or GnuTLS, I will integrate it and create NuGet packages for that. I can also try again with openssl. But I don't like to put too much effort in it, knowing that openssl 3 is soon to come. It is a complete re-write and will probably have a very different build system again.

**Comment by TaoziDB** [comment]
any update?

**Comment by lukasf** [comment]
Openssl3 is still not even in beta. I have also not seen any update in a long time. As I said, if someone succeeds in building GnuTLS or openssl, I would integrate it. But I am too busy right now to mess with these myself (lost quite some time on that already). I would give Openssl3 a try, if they can get it released.

**Comment by TaoziDB** [comment]
FYI, openssl3 was just released, let's hope that https support is coming soon :)

**Comment by lukasf** [comment]
Cool, thanks for letting me know @TaoziDB! I can also see that some work has been done in ffmpeg to support openssl 3.0. I am still rather busy, but I will try to take a chance on this within the next weeks.

**Comment by lukasf** [comment]
Oh man, it is really annoying that every lib brings its own build system with its own dependencies, limitations and specialities. Openssl uses perl for building. We already have perl in MSYS2. Openssl supports MSYS2 in general, and has configurations for MSVC compilers. But when compiling with MSVC toolchain, the Openssl build system requires a perl version that uses Windows path syntax with '\' instead of '/'. It refuses to compile with MSYS2 perl. I tried to hack the build script and got the basic compile steps working, but then comes lots of postprocessing code that is all hard coded with Windows paths - way too much to fix up.

So it looks like it is only possible to build Openssl with a Windows Perl installation (Strawberry Perl is recommended) and run in a PS or CMD environment. I really don't like the idea to blow up build dependencies, but it looks like this is the only way to get Openssl in.

**Comment by lukasf** [comment]
Luckily there is a portable version available of Strawberry Perl. I am working on an updated build script that will automatically download and configure missing dependencies such as MSYS2, Perl and NASM.

With Strawberry Pie I was able to build Openssl 3.0.0 for x64 UWP target and link it successfully with FFmpeg. However, the openssl build fails on x86 due to unresolved external methods (also on master branch). Not sure why that is happening. I need to look into that and maybe open an issue on the openssl project.

**Comment by lukasf** [comment]
Hi @TaoziDB, I have some good news for you: We have a first prerelease build that includes openssl 3.0.1! Theoretically, this should allow you to use https based streaming protocols. If you want to give it a try, check out the ffmpeg-4.4 branch and run one of the sample apps. Or in your app, update FFmpegInteropX.FFmpegUWP to 4.4.0-pre4.

**Comment by TaoziDB** [comment]
@lukasf, it works, thanks so much.

**Comment by lukasf** [comment]
Cool, glad to hear that it works!

**Comment by lukasf** [comment]
The PR is merged and https support is now officially available using FFmpegInteropX 0.9.3 and FFmpegInteropX.FFmpegUWP 4.4.100!
