### ISSUE TITLE
Can I use it with WPF?

### ISSUE THREAD

**Issue by takapdayon** [ffmpeginteropx/FFmpegInteropX#210]
I'm thinking of using WPF for streaming.
Will this library work fine with WPF?
thanks!

**Comment by lukasf** [comment]
You cannot directly render into a WPF MediaElement. But you can use XamlIslands to host a UWP MediaElement or MediaPlayerElement inside a WPF application. So generally this should work. I never tried it tough, so I cannot say if the performance will be exactly like in a native UWP application.

May I ask why you want to use WPF instead of UWP?

WinUI 3 will allow you to build desktop applications with native UWP UI. Alpha 2 is available, but it is missing MediaElement and MediaPlayerElement. Final release is scheduled for early 2021.

**Comment by lukasf** [comment]
WPF is technically dead. Further development will only happen on the UWP platform.

**Comment by mcosmin222** [comment]
Not really. Wpf is now fully supported in net core, so it is cross platform now, and on windows it will be able to host the same xaml controls that UWP would host, while not having any of the limitations of UWP, using winUI. 

So in a few years time it might be UWP that's going to be dead..

**Comment by jmvillagra** [comment]
It's not cross-platform.... it runs in .net core but only in windows. The only cross-platform thing is this UNO framework
Nevertheless, the desktop development future in windows is very uncertain... No idea what will come up from all this project reunion, win10x, uwp, windows store...

**Comment by jmvillagra** [comment]
It's not like they had to rewrite wpf to .net core...  Both .net core and .framwork supports the same .net standard, they just had to add support for the missing libraries that are not in .core via the Microsoft.Windows.Compatibility package and the same wpf can run in .core

As .net framework is "dead" and there are a lot wpf applications out there, this was a logical step so all those clients can evolve their apps via xaml islands / winui and take advantage of all the new language features + .net core optimizations

**Comment by lukasf** [comment]
I agree that the future of Windows UI platforms is pretty uncertain right now. But I am sure it is not going to be WPF, which has not received a single major new feature in years. They only ported it to .net core, so they can stop supporting the old .net framework. I was hoping for MS to buy UNO to make UWP truly cross-platform. But it does not look like this is going to happen anytime soon.

The old FileSystem classes are not part of WPF. WPF is only the UI layer. In a desktop app, you can combine UWP/WinUI with the old+fast FileSystem classes. No WPF needed for that. On the UI layer, in most cases, UWP has much better performance than WPF, due to all the optimizations received in the last years. Plus, WPF can never have 100% smooth animations, because it is written in C#, and the GC can and will kick in anytime during rendering.
