### ISSUE TITLE
video Frame Interpolation

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#219]
Hi, @lukasf 
Whether FFmpegInteropX can realize the conversion of video frame rate through frame interpolation.
I don't know if ffmpeginteropx supports using DirectShow filter (such as Dmitrirender) to implement frame interpolation.

**Comment by lukasf** [comment]
Hi @sudongg 
UWP is based on MediaFoundation. DirectShow filters cannot be used. Theoretically, we could add support for FFmpeg video effects, which has the "minterpolate" effect. But video effects would only work with the SW decoder, which does not make much sense. So I don't see us adding this util FFmpeg brings D3D11 video effects.

**Comment by mcosmin222** [comment]
Actually I may as well implement the filters for video as well, so it will be available for the software decoder. It's also interesting to see how this will work with the d3d11 decoder we have in place. 

Other than HEVC, it should work fine... 

But that been i have the time.

**Comment by lukasf** [comment]
I wouldn't put much work into this unless there is official D3D11 support for effects. But I am not against adding this, of course, if you want to do it. Maybe it would be possible to do decoding with D3D11, then copy the frame from GPU to CPU memory and apply effects in SW. Then we would keep HW decoding and still have effects. Only downside would be unneccessary memory copy, which would probably start to get painful with 4K video and higher. FullHD should be fine. But first step would be to get the effects working with SW decoder.

**Comment by lukasf** [comment]
I have tested the minterpolate filter on the ffmpeg-video-filters branch. Unfortunately, it does not really work. First, frame timestamps and durations are totally broken. We'd have to do manual calculation and patching of all frame times to get proper timings for playback. Second problem is that it plays the first 1-2 seconds normally, then it halts for 10-20 seconds (even on low res video), doing intense calculation, then it continues. This filter is not intended or suitable for real time playback, even on a quad core machine.

**Comment by sudongg** [comment]
@lukasf 
When I search for frame interpolation, few people mention the frame interpolation of ffmpeg. As far as I know, ffmpeg is better used for frame interpolation video output, and real-time frame interpolation is not completed.

I tried other frame interpolation solution, such as SVP, but the effect was not as good as Dmitrirender.
Dmitrirender can perform smooth frame interpolation on 4k video on my computer, and SVP will not be smooth.
The SVP project, after years of maintenance, the effect is still much worse than Dmitrirender. I think it should be quite difficult to achieve the effect of Dmitrirender.
There are similar solution to improve the frame rate, such as "motion interpolation" of MPV and "double frame" of potplayer. I can hardly see the effect.

**Comment by lukasf** [comment]
A few years back I looked into that topic as well. SVP was the only solution I could find, that was capable of doing real time frame interpolation for FullHD material. I don't know how they do it internally (custom code or library). It produced some artifacts, but it worked ok. 4K was not a topic at that time.

But in the end I did not use it, because my projector can do frame interpolation for me. And on lowest setting, it has the best effect for me. I don't like the butter smooth "video look" that most motion interpolation will lead to. On lowest setting, the projector will only do doubling to 48fps, and I think it only does it on zoom and pan scenarios, not on other small scale motion (acting). Zoom and pan is where 24fps hurts most. If that is eliminated, I get very smooth camera operation but none of the "video" look.

DmitriRender looks like a well done solution. It does motion interpolation on the GPU, which is much more effective, so it works even with high resolution video. But it is closed source, so there is no way how we could use it here.
