### ISSUE TITLE
CreateFromUriAsync error

### ISSUE THREAD

**Issue by sudongg** [ffmpeginteropx/FFmpegInteropX#221]
Hi, @lukasf 
CreateFromUriAsync crashed when I used it. The same link can be played using the default MediaSource.CreateFromUri.
I downloaded the latest master branch and found that opening the Uri link will pop up an error.
ffmpeg use 4.2.2, I tried to use 4.1.2 and got the same error.

**Comment by lukasf** [comment]
Hi @sudongg 
It usually has to do with the specific stream or format. I cannot tell what the problem is without a URI to reproduce. You can also check debug output. Sometimes FFmpeg will tell you there what is missing (e.g. https does not work because we don't have openssl).

My sample streams play fine using this method, so there is no general problem.

**Comment by sudongg** [comment]
@lukasf 
Test link:
http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4

The link can be played using MediaSource.CreateFromUri or MPC-HC, but it cannot be played using VLC. The console prompts:
```
main stream error: cannot resolve commondatastorage.googleapis.com port 80 :
http stream error: cannot connect to commondatastorage.googleapis.com:80
```
This problem should be related to my network. In my country, accessing Google requires VPN (virtual private network).

**Comment by lukasf** [comment]
Indeed it seems to be a network problem. I can play that file without issues. Maybe the UWP APIs pick up the proxy configuration from your browser. If you know your proxy configuration, you could try to add it to FFmpeg options like this: `Config.FFmpegOptions.Add("http_proxy", "http://ip:port/")`.
