### ISSUE TITLE
Get media stream by using rtmps protocal

### ISSUE THREAD

**Issue by tamsps** [ffmpeginteropx/FFmpegInteropX#240]
I'm using CreateFFmpegInteropMSSFromUri(uri, true, true) method to load media stream from server. Server stream video both RTMP and RTMPS protocal.  If I set URI = **rtmp**://xxx.xxx then method return was not null, But if I change URI = **rtmps**://xxxx.xxx then method return null.
How can I get media by using RTMPS protocal?
Thank you,
Tam

**Comment by lukasf** [comment]
Sorry for the late response, I somehow missed this issue. It currently fails because we don't have openssl in FFmpeg build. This is why we don't support the secure/encrypted transport protocols. This is a long standing issue and covered in #206. There were technical, as well as licensing issues that prevented us from integrating openssl in the past.

Openssl 3.0 has a new, much better license and technical improvements, which should make it possible to integrate it. I have recently started working on this, please follow #206 for updates if you are still interested.

Closing this one as duplicate of #206.

**Comment by lukasf** [comment]
Openssl is now available in FFmpegInteropX 0.9.3!
