### ISSUE TITLE
Second video doesn't play correctly, can hear audio but picture is of the previous video's last frame

### ISSUE THREAD

**Issue by mylastsong18** [ffmpeginteropx/FFmpegInteropX#243]
I am having an issue where when i load in a second video after loading a video, the second video fails to display a picture and just shows the last frame of the previous video. Tried the sample C# app and it's doing it as well. I am on Windows 11 22000.176 so perhaps there is an incompatibility somewhere. Using VS 2022 but tried VS 2019 with no change. Nothing in the output window when debugging and i'm not savvy enough to figure it out

Edit- I should note i am using the Nuget package, not referencing the project itself.

**Comment by lukasf** [comment]
It sounds like this happens with any file, correct? Then this is most probably a bug in the Windows 11 Insider Preview. Can you test this on a Windows 10 system (non-insider)? I can assure you that playing two arbitrary files in a row is not a problem at all with FFmpegInteropX. :-)

There have been lots of bugs in past insider previews, especially in the media playback area. That is why I do not use insider previews anymore. If Microsoft wants me to be a beta tester for their software, they have to pay me. It's too much trouble to do this for free.

If you don't have a regular Windows 10 installation, I can test the files here, if you upload them. But if it happens with any file, you don't need to upload, because I can tell you that on a regular system it will work 100%.

**Comment by mylastsong18** [comment]
It must be the insider build then. I am currently not home so i don't have access to my windows 10 system that i usually use to build. Doing some testing on a laptop i have here, but it is running the insider build. Thank you for confirming, I figured it must be that but wanted to open this issue just in case it wasn't. I will close it out

**Comment by lukasf** [comment]
I will install Windows 11 on a separate partition once the first official version is out, and do some testing. Let's hope that it will work on the final bits.
