### ISSUE TITLE
Question : Is it possible to convert a file with that library?

### ISSUE THREAD

**Issue by Osaxely** [ffmpeginteropx/FFmpegInteropX#259]
Hello, I'd like to know if that library allows to convert audio files between formats. If so, is there any documentation?

Thanks in advance.

**Comment by brabebhin** [comment]
Hi.

Yes. However,  you will only be able to create files that winRT supports.  Our library is decoding only,  no custom converter support,  but you can use builtin winRT apis. 

See
https://github.com/ffmpeginteropx/FFmpegInteropX/discussions/256

**Comment by Osaxely** [comment]
Hello, my apologies for the delayed response.
How would I decode a file for usage with an encoder? I am using that library: https://github.com/SteveLillis/.NET-Ogg-Vorbis-Encoder to encode the file to ogg.

Thanks in advance.

**Comment by brabebhin** [comment]
Currently, the only way to do transcoding is via winRT, using this class: https://docs.microsoft.com/en-us/uwp/api/windows.media.transcoding.mediatranscoder?view=winrt-22621 and this method https://docs.microsoft.com/en-us/uwp/api/windows.media.transcoding.mediatranscoder.preparemediastreamsourcetranscodeasync?view=winrt-22621#windows-media-transcoding-mediatranscoder-preparemediastreamsourcetranscodeasync(windows-media-core-imediasource-windows-storage-streams-irandomaccessstream-windows-media-mediaproperties-mediaencodingprofile)

There is no known way of using this trivially to transcode with other libraries, and quite frankly it would probably be easier to just implementing transcoding within this library instead of trying to adapt to others

**Comment by Osaxely** [comment]
I finally solved the problem using MP3Sharp (to decode) and Ogg-Vorbis Encoder to encode again. It works like a charm, it's fast and seems reliable.
All using Stream, so there is no problem with the file access permissions.
