### ISSUE TITLE
How to get Thumbnail from an URL Video?

### ISSUE THREAD

**Issue by XHotSniperX** [ffmpeginteropx/FFmpegInteropX#262]
How can I get the first frame of an URL (http) video file?

<img width="593" alt="image" src="https://user-images.githubusercontent.com/8674737/164894166-cf49a01d-05ca-44ac-bf3d-c4a195eeace1.png">

I would suggest to give the possibility to create a FrameGrabber from URL. That would fix this problem.

**Comment by brabebhin** [comment]
Extract thumbnail actually only extracts album art frames.
It should technically be possible to get a frame grabber from url, I'll see if i can get something done if i have the time.

**Comment by XHotSniperX** [comment]
I just created a PR (see [263](https://github.com/ffmpeginteropx/FFmpegInteropX/pull/263)). With that I can create the frame grabber from url. It worked in my app but you need to be careful not to open too many frame grabbers quickly otherwise you might get some exceptions...

**Comment by brabebhin** [comment]
Looks good, thanks.  @lukasf  will also have to approve.
Technically if you need multiple frames from the same stream, you can reuse the same framegrabber instance.

I think the biggest issue with uri is if you can seek the stream.  Not all uris will describe a seekable stream.

**Comment by lukasf** [comment]
Thanks @XHotSniperX, looks good!

I have thought about seekable vs non-seekable streams as well. Surprisingly, there is no API or flag in ffmpeg, to check if a file/stream is seekable. Our implementation in `InitFFmpegContext()` checks if we have a duration > 0, and allows seeking if that is true. Not sure if that is a good assumption, but so far there have not been any complaints. At least it prevents seeking on live streams, which do not have a duration.

We might consider adding a CanSeek property to the frame grabber, which returns the same duration check. But on the other hand, since the decision logic is so poor, we could also skip this until someone finds a proper way.
