### ISSUE TITLE
RTSP stream handled incorrectly when there is a TCP reset or retransmission while using the system decoder.

### ISSUE THREAD

**Issue by Baileymnm1999** [ffmpeginteropx/FFmpegInteropX#264]
I am using this library to stream an rtsp stream over a software defined router. It works fine for regular streaming, but the router has multiple WAN links, and if one goes down it is configured to send traffic over another link and maintain tcp sessions by injecting a tcp reset or retransmission. If I use the library provided software decoder this works okay, though the quality of the video is poor. When trying to use the system decoder the stream gets dropped when the tcp reset or retransmission is injected. Is this an issue with the system decoder or with the library and how can I remedy? Here is how the decoder and etc were created.
```c#
        private void InitializeMediaPlayer()
        {
            FFmpegInteropLogging.SetDefaultLogProvider();
            configuration = new FFmpegInteropConfig()
            {
                MaxVideoThreads = 8,
                SkipErrors = uint.MaxValue,
                DefaultBufferTime = TimeSpan.Zero,
                FastSeek = true,
                VideoDecoderMode = VideoDecoderMode.Automatic
                
            };
            configuration.FFmpegOptions.Add("tune", "zerolatency");
            configuration.FFmpegOptions.Add("flags", "low_delay");
            configuration.FFmpegOptions.Add("rtsp_flags", "prefer_tcp");
            configuration.FFmpegOptions.Add("fflags", "discardcorrupt+shortest+sortdts+ignidx+nobuffer");
            InitializeMediaSource(sourceUri.ToString());
            submitButton.Click += SubmitButton_Click;
        }

        private async void InitializeMediaSource(string uri)
        {
            decoder = await FFmpegInteropMSS.CreateFromUriAsync(uri, configuration);

            var mediaPlayer = new Windows.Media.Playback.MediaPlayer();
            mediaPlayerElement.SetMediaPlayer(mediaPlayer);
            mediaPlayer.AutoPlay = true;
            mediaPlayer.Source = decoder.CreateMediaPlaybackItem();
        }
```

**Comment by brabebhin** [comment]
Interesting. The library does demux for all three decoder modes, so there should be no difference between the behavior of software decoding over system decoder.

I don't see any obvious problem in your setup. You could use the directx hardware decoder, which should be smoking both the software and the system decoder in terms of performance. What kind of video do you stream?

**Comment by Baileymnm1999** [comment]
The video is fine with the hardware decoder. If I use the decoder shipped with the library it's choppy and has lots of issues with the picture quality, blocking, static, etc. If the software decoder was fast and quality enough I would just use that, but this is 720p video and so the hardware decoder is needed.

**Comment by Baileymnm1999** [comment]
Do you think it could have something to do with the hardware device failing or resetting in some way because of how the library is handling the data stream which then causes the net code to close the socket?

**Comment by brabebhin** [comment]
Can you fetch the stream info of the video stream? Or feels weird that the software decoders can't handle it.

I'm interested in the decoder it autoselects (I'd expect to be the d3d11hardware decoder) and the stream format.

**Comment by Baileymnm1999** [comment]
What info in particular are you looking for? It's either a 480p or 720p video running around 30fps (not sure on this exactly, could be lower) and it's being server via rtsp-simple-server over tcp. H264 encoded.

**Comment by brabebhin** [comment]
The ffmpeginterop instance will expose StreamInfos for all video,  audio and subtitle streams in your file. These StreamInfos will tell you things about the decoder. For H264,  hardware decoding should be available within your GPU.

What GPU do you have?

**Comment by Baileymnm1999** [comment]
This app is tested on my laptop rtx 3060m ans deployed to a hl2 which supports h264 hardware decoding. The issue is present on both devices. I can pull the stream info for you later today hopefully. Busy for the next hour or so.

**Comment by lukasf** [comment]
There are actually three decoder pipelines: Software, D3D11 (HW decoding through FFmpeg APIs +  D3D11) and System Decoder (HW decoding using OS codecs). Fetching the StreamInfo after playback has started should tell us which of the three is actually used.

If it is the D3D11 decoder, it is possible to debug deeper any maybe handle this somehow. If it is SystemDecoder, then this is a black box, we don't have any way to handle errors there.

**Comment by brabebhin** [comment]
Another test to try is to create a mediaplaybackitem from the url using mediasource.fromuri and see of it behaves the same as the system decoders. If it does, then it's pretty clear this is an os problem. It wouldn't be the first.

It still is weird the d3d11 decoder isn't kicking in and doing the decoding.

**Comment by Baileymnm1999** [comment]
Okay thanks for the suggestions, I will try them and report back. @lukasf if it is using the system decoders while having this issue, is it not possible that the library code managing the video stream could be inducing an error, specifically if the issue only occurs with the hardware decoder?

**Comment by brabebhin** [comment]
Actually the OS codecs may or may not be hardware accelerated. The OS also does software decoding if no hardware acceleration is available.

**Comment by lukasf** [comment]
Yeah it is really important to know which decoder pipeline we are talking about, because they work so very different. I am still not sure which one is actually used in your scenario.

If you set VideoDecoderMode to "Automatic" (as seen in your code sample), then it should select the d3d11 based GPU decoder. Here we have most of the stream reading and decoding in our hands. If this is what you are using and where the problem occurs, we have some chances of analyzing and maybe fixing this.

If you are using "AutomaticSystemDecoder" or "ForceSystemDecoder", then we are using the OS codecs. In that mode, we pass down the raw stream data to OS codecs. The OS codecs will handle all the decoding (possibly GPU assisted), and we have no control over how they do it or what happens in case of errors.

**Comment by Baileymnm1999** [comment]
So when I described which decoders worked and which did not earlier is because I tried all three of those modes. The only one that worked was ForceSystemDecoder

**Comment by lukasf** [comment]
Okay that is interesting.

Best would be to use d3d11 instead. Maybe we can find out why it is not used. When setting "Automatic", can you put a breakpoint in `OnStarting()` and see if the initialization of the avHardwareContext runs successfully and that the device is successfully assigned to the stream (`stream->SetHardwareDevice`)?

Let's maybe also check if we error out somewhere and what the error code is, when using ForceSystemDecoder. Put two breakpoints in `CompressedSampleProvider::CreateNextSampleBuffer`, one after `GetNextPacket`, one after `CreateBufferFromPacket`. Set both breakpoints as conditional "hr != 0" (right-click on breakpoint -> Conditions). Run it and provoke the error situation, check if one of the breakpoints is hit and report the hr value. If it is us who error out due to illegal packet format, we might be able to add a retry mechanism here, similar to what we have in the UncompressedSampleProvider.

**Comment by Baileymnm1999** [comment]
I apologize @lukasf I spoke incorrectly earlier. The only mode that worked was ffmpegSoftwareDecoder.

**Comment by lukasf** [comment]
But GPU decoding works with ForceSystemDecoder, right? It's just that the stream is dropped on reset. Does GPU decoding also work with "Automatic"?

**Comment by Baileymnm1999** [comment]
Yes, yes, and yes

**Comment by lukasf** [comment]
Oh okay. Interesting. Let me clarify:

ForceSystemDecoder -> Fast GPU decoding, stream dropped on reset
Automatic -> Fast GPU decoding, stream dropped on reset
ForceFFmpegSoftwareDecoder -> Slow decoding, NO drop on reset

**Comment by Baileymnm1999** [comment]
Exactly. To go even a bit further, I can verify that the stream was actually picked up on the secondary Wan link that was available via the software router dashboard when using the ffmpegsoftwaredecoder. Works completely as expected, just slow.

**Comment by lukasf** [comment]
Now this is pretty confusing, because in "Automatic" mode, the implementation is very very similar to SoftwareDecoder mode. Actually most of it is exactly the same, especially everything stream / packet related. If it works with SoftwareDecoder, I would sure have expected it to work in "Automatic" as well. Previously I thought that Automatic works, but it does not give you GPU acceleration (falling back to SoftwareDecoder).

ForceSystemDecoder on the other hand is totally different from the implementation and way of working. Only similarity to "Automatic" is that it also uses the GPU at some point. Very weird that they should both show the same break on reset behavior.

I am a bit out of ideas here right now, need to give this some thought...

**Comment by brabebhin** [comment]
I don't see how the GPU might fail over the network change. These should be totally independent. And the GPU momentarily failing should be a pretty visible event, like the entire screen flashing.

I think the issue still lies in the decoding of packages. It might be that after the reset, the packages are no longer valid, and while the software decoder may attempt to fix them, the hardware decoder is probably unable to do that.

**Comment by lukasf** [comment]
I also cannot see how TCP stream status could trigger a GPU device reset. The two are not related at all, the GPU does not even know where the data comes from.

Please verify that indeed both GPU decoding paths show the same behavior and watch for messages in output window.

For ForceSystemDecoder, you could also try this:

> Let's maybe also check if we error out somewhere and what the error code is, when using ForceSystemDecoder. Put two breakpoints in `CompressedSampleProvider::CreateNextSampleBuffer`, one after `GetNextPacket`, one after `CreateBufferFromPacket`. Set both breakpoints as conditional "hr != 0" (right-click on breakpoint -> Conditions). Run it and provoke the error situation, check if one of the breakpoints is hit and report the hr value. If it is us who error out due to illegal packet format, we might be able to add a retry mechanism here, similar to what we have in the UncompressedSampleProvider.

**Comment by lukasf** [comment]
Closing this for now. Feel free to re-open if you have questions.
