### ISSUE TITLE
Adding the FFmpegInteropX.FFmpegUWP NuGet package to UWP app,  cause release build failed

### ISSUE THREAD

**Issue by yikuo123** [ffmpeginteropx/FFmpegInteropX#315]
Step:

1. Add the FFmpegInteropX.FFmpegUWP NuGet package
2. Project - Publish- Create App Packages

```
Microsoft.NetNative.targets(809,5): error : Internal compiler error: MCG0023:UnresolvableAssemblyReference Unresolvable assembly reference 'Assembly(Name=Microsoft.Graphics.Canvas, Version=255.255.255.255, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime)' found. Please check the references in your build system. A reference is either missing or an assembly is missing an expected type
```

**Comment by brabebhin** [comment]
Hi,

I tried and failed.
Can you provide a sample project?

Thanks.

**Comment by brabebhin** [comment]
Updating to latest preview version seems to fix the issue.

**Comment by lukasf** [comment]
Thinking about this. We really do have a dependency on Win2d, because of the BasicVideoEffect. But it is not declared on the NuGet package. Even if the build succeeds with latest preview, at runtime it would sure fail, at least when using BasicVideoEffect. Not sure though why it builds with master branch releases, maybe there are some differences on how .NET Native handles C++/WinRT, compared to C++/CX.

I think most people use this lib with the project reference. But we need to make sure that NuGet works as well. And as long as we include BasicVideoEffect with the lib, we must declare it on the NuGet as well.

**Comment by lukasf** [comment]
Closing this since it is fixed in latest prerelease packages.
