### ISSUE TITLE
RTSP stream disconnects without any error

### ISSUE THREAD

**Issue by don-pironet-hatch** [ffmpeginteropx/FFmpegInteropX#368]
I'm encountering an issue where my RTSP sessions disconnect from the device (some sort of IOT live camera) after a brief period, approximately 2 minutes or so.
Before implementing the library I started from this FFmpeg command which works fine without any disconnects.

`ffplay -fflags nobuffer -flags low_delay -tune zerolatency -probesize 32 -preset ultrafast rtsp://192.168.3.1:8554/test.mp4`

FFmpegInteropX code:

```
            MediaSourceConfig configuration = new MediaSourceConfig()
            {
                MaxVideoThreads = 8,
                SkipErrors = uint.MaxValue,
                DefaultBufferTime = TimeSpan.Zero,
                FastSeek = true,
                VideoDecoderMode = VideoDecoderMode.ForceFFmpegSoftwareDecoder, // Can't use the GPU otherwise immediately disconnect
            };

            configuration.FFmpegOptions.Add("tune", "zerolatency");
            configuration.FFmpegOptions.Add("flags", "low_delay");
            configuration.FFmpegOptions.Add("probesize", 32);
            configuration.FFmpegOptions.Add("preset", "ultrafast");

            var decoder = await FFmpegMediaSource.CreateFromUriAsync("rtsp://192.168.3.1:8554/test.mp4", configuration);
            var mediaStreamSource = decoder.GetMediaStreamSource();
            mediaStreamSource.BufferTime = TimeSpan.FromSeconds(0);

            _mediaPlayer = new MediaPlayer();
            _mediaPlayer.Source = MediaSource.CreateFromMediaStreamSource(mediaStreamSource);
            _mediaPlayer.RealTimePlayback = true;
            _mediaPlayer.Play();
            
            mediaPlayerElement.SetMediaPlayer(_mediaPlayer);
```

There are no crashes, and the logs don't show any errors. The only observable issue is the disconnection of the RTSP stream.
What could be the root of the problem, and how can I go about troubleshooting it?

**Comment by brabebhin** [comment]
The RealTimePlayback property of MediaPlayer has some funny side effects, I'd try without that.

I would also try with a MediaPlaybackItem from the FFmpegMediaSource directly (the CreateMediaPlaybackItem method) -the GetMediaStreamSource API is sort of kinda deprecated and only there because some people need it for transcoding purposes.

Do you reference our project directly or the nuget packages? The nuget packages are a little out dated while we prepare for the 2.0 release, referencing the project directly will allow you to use the latest features and bug fixes.

**Comment by don-pironet-hatch** [comment]
I switched to the CreateMediaPlaybackItem method like you suggested and I turned off the realtimeplayback. I'm now being able to use the Automatic VideoDecoder so that I use the GPU without immediately disconnecting. But still after 2 minutes there is a disconnect. I'm using the nuget packages so I will now try to remove them and do a git clone and reference the project. I will keep you up to date. Thanks for your help already.

**Comment by don-pironet-hatch** [comment]
I'm having troubles adding the project as a reference. 
Steps that I did:

- git clone https://github.com/ffmpeginteropx/FFmpegInteropX.git
- Right click my solution > add > existing project > Source\FFmpegInteropX.vcxproj
- In my main project > right click references > add reference > on the lefst side projects > tick the checkbox FFmpegInteropX

Visual studio throws following error: a reference to 'FFmpegInteropX' could not be added. The method or operation is not implemented.  I also notice that FFmpegInteropX.vcxproj has missing NuGet Packages but even after a NuGet restore the error still exist.

**Comment by brabebhin** [comment]
In order to directly add the project, you need to follow these steps:
1. Clone the project (you did)
2. Add the FFmpegInteropX as reference to your application
3. If your application is using winUI 3, add the following lines to your csproj. You also need to install the CsWinRT package.

> 	<PropertyGroup>
> 		
> 		<CsWinRTIncludes Condition="'$(CsWinRTIncludes)' == ''">@(CsWinRTRemovedReferences->'%(FileName)')</CsWinRTIncludes>
> 
> 	</PropertyGroup>
> 
> 	<Target Name="IncludeFFmpegInteropXInRuntimesFolder" BeforeTargets="GetCopyToOutputDirectoryItems" Condition="'$(Configuration)'=='Debug'">
> 		<ItemGroup>
> 			<AllItemsFullPathWithTargetPath Include="$(OutDir)FFmpegInteropX.dll">
> 				<TargetPath>runtimes\win10-$(Platform)\native\FFmpegInteropX.dll</TargetPath>
> 				<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
> 			</AllItemsFullPathWithTargetPath>
> 			<AllItemsFullPathWithTargetPath Include="$(OutDir)FFmpegInteropX.pdb">
> 				<TargetPath>runtimes\win10-$(Platform)\native\FFmpegInteropX.pdb</TargetPath>
> 				<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
> 			</AllItemsFullPathWithTargetPath>
> 		</ItemGroup>
> 	</Target>

**Comment by don-pironet-hatch** [comment]
I will try that this evening. We are using WinUI 2. 
That would be nice if the latest version could be released.

**Comment by brabebhin** [comment]
Winui 2 as in UWP?

**Comment by don-pironet-hatch** [comment]
Yes it's a UWP app.

**Comment by brabebhin** [comment]
Ok, then simply reference the project. You also need to install VS features to build. Check the readme

**Comment by lukasf** [comment]
The reason why playback stops is that you don't store the FFmpegMediaSource instance ("var decoder" in your code) in a field. The current official build still has the restriction that you must keep a reference to the FFmpegMediaSource as long as you play it, to prevent it from being garbage collected. If you don't, playback will just stop after a random time, often about a minute or two.

The upcoming version 2.0 won't have this restriction anymore, but it is not finished yet. So just store your decoder in a field instead of a local var, then playback should work fine.

**Comment by don-pironet-hatch** [comment]
@brabebhin I've installed everything according to the readme. Just that you know the links to download the Visual C++ Redistributable for Visual Studio 2010 are not working anymore. I've found those online and when I try to install those it says that I already have a newer version. Don't know if this is a problem or not. Because I would still like to reference the latest version to see the difference and see debug information.

@lukasf Thank you so much this indeed solves the problem. I mistakenly believed (a rookie mistake), that it wouldn't be subject to garbage collection since it was being utilized by MediaSource.CreateFromMediaStreamSource. Any timings when the 2.0 version is going to be released?

**Comment by lukasf** [comment]
I think you don't need the C++ redists anymore, since Microsoft now has these all-in-one redist. Also, they were only required for building ffmpeg itself, not for opening or building our lib. The only things important for the lib are the UWP workload plus the UWP c++ build tools. What happens when you directly open the FFmpegInteropX.sln file?

About the 2.0 version, there are still some things that need to be decided, especially regarding the nuget package architecture. We want to fully support Desktop and WinUI 3.0 apps, and that requires some considerations. I hope we will see it this year, but I won't make promises.

**Comment by brabebhin** [comment]
Good catch with the GC, completely forgot how far behind the live version is!
