### ISSUE TITLE
CheckRecommendedVersion

### ISSUE THREAD

**Issue by pashmak73** [ffmpeginteropx/FFmpegInteropX#93]
Hi, I just wondering to know what is `FFmpegVersionInfo.CheckRecommendedVersion();` and what suppose to do?
I checked [FFmpegVersionInfo.h](https://github.com/ffmpeginteropx/FFmpegInteropX/blob/master/FFmpegInterop/FFmpegVersionInfo.h) and as I understand it just pass some info to `CheckFFmpegVersion`.

Should I add this to my project or not? I'm using FFmpeg 4.1.1.

**Comment by lukasf** [comment]
Hi @pashmak73, what CheckRecommendedVersion does is to verify that your ffmpeg build is the recommended version or higher. If you run the app with FFmpeg 4.0 and call CheckRecommendedVersion, an exception would be thrown. So this can help remind you to update your ffmpeg dlls, whenever the recommended version has changed. I'd recommend you to add this to your app startup code. But in the end it's up to you.

Please note that the library always automatically checks for the minimum version (which is 4.0 currently). So if you run this with e.g. ffmpeg 3.4 (which is not compatible with the current library due to API changes) then an exception will be thrown when creating an instance of FFmpegInteropMSS. But you could run the library with ffmpeg 4.0 dlls.
